<?php
$productCollection = Mage::registry('products');
$totalPage = Mage::registry('totalPage');
$wishID = Mage::registry('wishID');
$isOwned = Mage::registry('');
$customer = Mage::getSingleton('customer/session')->getCustomer();
$customer_name = $customer->getName();
$customer_id = $customer->getId();
$isOwned = Mage::registry('owned');
?>
<div class="breadcrumbs">
    <ul>
        <div class="tekshop-cat-header-breadcrumbs">
            <div class="tekshop-cat-header-img">
                <img src="/skin/frontend/default/tekshop/images/header-icon.png">
            </div>
            <div class="tekshop-breadcrumb-header">
                <li class="category613">
                    <strong>Sản phẩm yêu thích của <?php echo $customer_name ?></strong>
                </li>
            </div>
        </div>
    </ul>
</div>

<input type="hidden" id="currentPage" value="1"/>
<input type="hidden" id="totalPage" value="<?php echo $totalPage; ?>"/>
<input type="hidden" id="wishID" value="<?php echo $wishID; ?>"/>
<?php if (!$productCollection): ?>
    <div class="cart-empty">
        <img class="cart-empty-img">
        <h1 class="cart-empty-text">Danh sách sản phẩm yêu thích của bạn đang trống !</h1>
        <h1 class="cart-empty-text mb-20">
            <!--<a class="click-here btn btn-tekshop btn-cart-empty-more-product" href="http://tekshop.local/tek/">
                Chọn thêm sản phẩm
            </a>-->
        </h1>
    </div>
<?php else: ?>
<div class="col-md-12 col-xs-12 col-sm-12">
    <div class="search-wishlist">
        <div class="search-wish-pc">
            <span class="btn-wish-search" id="btn-search-wish" title="Tìm kiếm"><i class="fa fa-search fa-2"
                                                                                   aria-hidden="true"></i></span>
            <input id="bp-search-input" type="text" class="bp-search-input search-wish"
                   placeholder="Tìm kiếm sản phẩm ưa thích">
        </div>
    </div>
    <div class="text-center loading-search" title="Đang tải"
         style="display: none;margin-top: 15px;margin-bottom: 15px;">
        <img src="http://test.tekshop.vn/skin/frontend/default/tekshop/images/loading.gif">
    </div>
</div>
<div class="col-md-12 col-xs-12 bp-products-content no-padding">
    <div class="search-wish-message" style="display: none"> Không tìm thấy kết quả cho <span id="none-keyword"></span>
    </div>
    <div class="search-content"></div>
    <div class="origin-list">
        <div class="load-after-remove">
            <?php foreach ($productCollection as $_product): ?>
                <div class="col-md-12 col-xs-12 bp-selected-item wishlist-show">
                    <div class="col-md-2 col-xs-2 a-center no-padding">
                        <img class="bp-product-image"
                             src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(150, 150); ?>"
                             alt="<?php echo $this->escapeHtml($this->getImageLabel($_product, 'small_image')) ?>"
                             title="<?php echo $this->escapeHtml($this->getImageLabel($_product, 'small_image')) ?>"
                        />
                    </div>
                    <div class="col-md-7 col-xs-8">
                        <div class="bp-product-name">
                            <a href="<?php echo $_product->getProductUrl() ?>"
                               data-name="<?php echo $_product->getName() ?>"
                               data-id="<?php echo $_product->getId() ?>"
                               data-price="<?php echo $_product->getFinalPrice() ?>"
                               target="_blank"><?php echo $_product->getName(); ?></a>
                        </div>
                        <div class="bp-product-old-price">
                            <?php if ($_product->getPrice() != $_product->getFinalPrice()): ?>
                                <?php echo number_format($_product->getPrice(), 0, ",", ".") . " đ"; ?>
                            <?php endif; ?>
                        </div>
                        <div class="bp-product-regular-price">
                            <?php echo number_format($_product->getFinalPrice(), 0, ",", ".") . " đ"; ?>
                        </div>
                    </div>
                    <div class="col-md-3 col-xs-2 a-right no-padding">
                        <button type="button" class="btn btn-success bp-change-btn wish-add-to-cart"
                                product-id="<?php echo $_product->getId() ?>" style="margin-top: 10%">
                            <img class="bp-ajax-loader-customize bp-ajax-8059 loading" title="Đang tải"
                                 src="http://tekshop.vn/skin/frontend/default/tekshop/images/ajax-loader.gif" width="14"
                                 height="14" style="display: none;">
                            <span class="hidden-mobile display-inline">Thêm <span
                                        class="hidden-1200">vào giỏ hàng&nbsp;</span>
                        <i class="fa fa-angle-right bp-i-8059"></i>
                    </span>
                            <i class="fa fa-plus display-mobile"></i>
                        </button>
                        <?php if ($isOwned): ?>
                            <button product-id="<?php echo $_product->getId() ?>" alt="Xóa" title="Xóa khỏi danh sách"
                                    type="button" class="remove-wishlist" aria-hidden="true"
                                    deluminate_imagetype="png"></button>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="additionItem">
        <div class="additionContent"></div>
    </div>
    <div>
    </div>
    <?php if ($totalPage != 1): ?>
        <div class="text-center load-more-products-text">
            <button type="button" class="btn btn-default btn-viewmore btn-loadmore-list">XEM THÊM
                SẢN PHẨM
            </button>
        </div>
        <div class="text-center load-more-products" title="Đang tải" style="display: none;">
            <img class="mt-13" src="http://tekshop.vn/skin/frontend/default/tekshop/images/loading.gif">
        </div>
    <?php endif; ?>
    <?php endif; ?>
    <script>
        var $j = jQuery.noConflict();
        bindAddToCart();
        bindRemoveWishlist();
        $j('.btn-loadmore-list').on('click', function (e) {
            $j('.btn-loadmore-list').hide();
            $j('.load-more-products').show();
            var currentPage = Number($j('#currentPage').val());
            var totalPage = Number($j('#totalPage').val());
            var wishId = $j('#wishID').val();
            $j.ajax({
                url: '/tek/favourite/index/loadMore',
                data: {
                    'wishID': wishId,
                    'currentPage': currentPage
                },
                success: function (data) {
                    $j('.additionContent').append(data);
                    $j('.btn-loadmore-list').show();
                    $j('.load-more-products').hide();
                    currentPage = Number(currentPage) + 1;
                    if (currentPage === totalPage) {
                        $j('.load-more-products-text').hide();
                    } else {
                        $j('#currentPage').val(currentPage);
                    }
                    $j('load-more-products').hide();
                    bindAddToCart();
                    bindRemoveWishlist();
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    console.log("Status: " + textStatus);
                    console.log("Error: " + errorThrown);
                    $j('load-more-products').hide();
                }
            });
            e.preventDefault();
            e.stopPropagation();
        });
        function bindRemoveWishlist() {
            $j('.remove-wishlist').bind('click', function (e) {
                var product = $j(this).attr('product-id');
                swal({
                        title: "Xóa khỏi danh sách yêu thích ?",
                        text: "Bạn có muốn xóa sản phẩm khỏi danh sách yêu thích ?",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: '#DD6B55',
                        confirmButtonText: 'Xóa sản phẩm',
                        cancelButtonText: "Hủy bỏ",
                        closeOnConfirm: false,
                        closeOnCancel: false
                    },
                    function (isConfirm) {
                        if (isConfirm) {
                            $j.ajax({
                                method: 'POST',
                                url: '/tek/favourite/index/removeFromWishList',
                                data: {
                                    'product': product,
                                    'customer': <?php echo $customer_id?>,
                                    'currentPage': Number($j('#currentPage').val())
                                },
                                success: function (data) {
                                    data = JSON.parse(data);
                                    if (data['success']) {
                                        // reload
                                        $j('.additionItem').html('<div class=\"additionContent\"></div>');
                                        $j('.load-after-remove').html($j.parseHTML(data['data']));
                                        bindAddToCart();
                                        bindRemoveWishlist();
                                        swal("Thành công!", "Đã loại bỏ sản phẩm khỏi danh sách yêu thích!");
                                        setTimeout(function () {
                                            swal.close();
                                        }, 500);
                                    }
                                    else {
                                        swal("Không thành công!", data.failed,);
                                        setTimeout(function () {
                                            swal.close();
                                        }, 1000)
                                    }
                                },
                                error: function (XMLHttpRequest, textStatus, errorThrown) {
                                    console.log("Status: " + textStatus);
                                    console.log("Error: " + errorThrown);
                                    $j('.loading-wish').hide();
                                }
                            });
                        }
                        else {
                            swal.close();
                        }
                    });

                e.preventDefault();
                e.stopPropagation();
            });
        }

        function bindAddToCart() {
            $j('.wish-add-to-cart').bind('click', function (e) {
                var product_id = $j(this).attr('product-id');
                $j('.wish-add-to-cart').prop('disabled', true);
                $j('.ajax-loader-atc').show();
                $j('.loading').show();
//        var purchaseQty = parseInt($j('.qty-selector-input').val());
                /* Enhanced ecommerce add to cart*/
                /**
                 * Measure adding a product to a shopping cart by using an 'add' actionFieldObject
                 * and a list of productFieldObjects.
                 */
                /* End Enhanced ecommerce add to cart*/
                $j.ajax({
                    url: '/tek/checkout/cart/addAjax/',
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        form_key: "<?php echo Mage::getSingleton('core/session')->getFormKey() ?>",
                        product: product_id,
                        related_product: '',
                        qty: 1
                    },
                    success: function (response) {
                        $j('.ajax-loader-atc').hide();
                        $j('.wish-add-to-cart').prop('disabled', false);
                        if (response.message !== '') {
                            $j('.add_to_cart_messages').empty();
                            if (response.error_flg == 0) {
                                if (win.width() < 500) {
                                    window.location = '<?php echo $this->getUrl('checkout/cart') ?>';
                                } else {
                                    $j('.add_to_cart_messages').append("<li class='success-msg'><ul><li><span>" + response.message + "</span></li></ul></li>");
                                }
                            }
                            else {
                                if (response.message == 'Vui lòng lựa chọn thuộc tính sản phẩm!') {
                                    $j('.attribute-error-message').html(response.message);
                                    $j('.attribute-error-message').show();
                                }
                                else {
                                    if (response.message == 'Please specify the product\'s option(s).') {
                                        response.message = 'Vui lòng lựa chọn thuộc tính sản phẩm!';
                                    }
                                    $j('.add_to_cart_messages').append("<li class='error-msg'><ul><li><span>" + response.message + "</span></li></ul></li>");
                                    if (win.width() < 500) {
                                        $j('#messages_product_view').insertAfter('.share-block');
                                        $j("html, body").animate({scrollTop: $j('#messages_product_view').offset().top + 15}, 500);
                                    }
                                    $j('.btn-tekshop').addClass('opa-1');
                                }
                            }
                        }
                        swal("Thành công!", "Đã thêm vào giỏ hàng!");
                        setTimeout(function () {
                            swal.close();
                        }, 500);
                        // Update Subtotal
                        $j('.cart-pr-subtotal').empty();
                        $j('.cart-pr-subtotal').html(addCommas(response.sub_total) + ' ₫');

                        // Update Grandtotal
                        $j('.cart-pr-grandtotal').empty();
                        $j('.cart-pr-grandtotal').html(addCommas(response.grand_total) + ' ₫');

                        // Update shopping cart body
                        $j('#shopping-cart-body').empty();
                        $j('#shopping-cart-body').append(response.ex_html);

                        // Update shopping cart header
                        $j('#shopping-cart-header').empty();
                        $j('#shopping-cart-header').append(response.ex_header_html);

                        $j('.wish-add-to-cart').prop('disabled', false);
                        $j('.loading').hide();
                    }
                });
                e.preventDefault();
                e.stopPropagation();
            });
        }

        function searchWishList() {
            var searchQuery = $j('.search-wish').val().trim();
            var wishlistId = $j('#wishID').val();
            if (searchQuery.length === 0 || searchQuery === '') {
                if ($j('.origin-list').is(":visible")) {
                    return;
                }
                else {
                    if ($j('.search-wish-message').is(':visible')) {
                        $j('.search-wish-message').hide();
                    }
                    $j('.search-content').hide();
                    $j('.origin-list').show();
                    $j('.btn-loadmore-list').show();
                    return;
                }
            }
            else {
                if (searchQuery.length < 4) {
                    swal("", "Từ khóa tối thiếu 4 ký tự");
                    setTimeout(function () {
                        swal.close();
                    }, 4000);
                    return;
                } else {
                    $j('.loading-search').show();
                    $j.ajax({
                        url: '/tek/favourite/index/searchInWishlist',
                        data: {
                            'wishlistId': wishlistId,
                            'searchQuery': searchQuery
                        },
                        success: function (data) {
                            data = JSON.parse(data);
                            if (data.success) {
                                if ($j('.origin-list').is(":visible")) {
                                    $j('.origin-list').hide();
                                }
                                $j('.btn-loadmore-list').hide();
                                $j('.search-content').html(data.data);
                                if (!$j('.search-content').is(":visible")) {
                                    $j('.search-content').show();
                                }
                                if ($j('.search-wish-message').is(':visible')) {
                                    $j('.search-wish-message').hide();
                                }
                                $j('.loading-search').hide();
                            }
                            if (data.notfound) {
                                if ($j('.search-content').is(":visible")) {
                                    $j('.search-content').hide();
                                }
                                if ($j('.origin-list').is(":visible")) {
                                    $j('.origin-list').hide();
                                }
                                if (searchQuery.includes('<') || searchQuery.includes('>') || searchQuery.includes('script')) {
                                    $j('#none-keyword').html(" từ khóa trên");
                                    $j('.search-wish-message').show();
                                    $j('.search-content').html("");
                                    $j('.loading-search').hide();
                                    return;
                                }
                                $j('#none-keyword').html(searchQuery);
                                $j('.search-wish-message').show();
                                $j('.search-content').html("");
                                $j('.loading-search').hide();
                            }
                            if (data.error) {
                                // Swal ok no ??
                                $j('.loading-search').hide();
                            }
                        },
                        error: function (XMLHttpRequest, textStatus, errorThrown) {
                            console.log("Status: " + textStatus);
                            console.log("Error: " + errorThrown);
                            $j('.loading-search').hide();
                        }
                    });
                }
            }
        }
        $j('.search-wish').bind('keypress', function (e) {
            if (e.keyCode === 13) {
                searchWishList();
            }
        });
        $j('.btn-wish-search').on('click', function (e) {
            searchWishList();
            e.preventDefault;
            e.stopPropagation();
        });

        function addCommas(str) {
            var parts = (str + "").split("."),
                main = parts[0],
                len = main.length,
                output = "",
                first = main.charAt(0),
                i;

            if (first === '-') {
                main = main.slice(1);
                len = main.length;
            } else {
                first = "";
            }
            i = len - 1;
            while (i >= 0) {
                output = main.charAt(i) + output;
                if ((len - i) % 3 === 0 && i > 0) {
                    output = "." + output;
                }
                --i;
            }
            // put sign back
            output = first + output;
            // put decimal part back
            if (parts.length > 1) {
                output += "." + parts[1];
            }
            return output;
        }
    </script>