<div>
    <center>
        <button onclick="location.href = '<?php echo Mage::getUrl('*/*/get') ?>'"
                type="button">Lấy dữ liệu
        </button>
        <button onclick="location.href = '<?php echo Mage::getUrl('*/*/run') ?>'"
                type="button">Cập nhật
        </button>
        <button onclick="location.href = '<?php echo Mage::getUrl('*/*/success') ?>'"
                type="button">Xem kết quả
        </button>
        <p>Giá sản phẩm sẽ được cập nhật từ bên Phong Vũ.</p>
        <p>Chức năng này sẽ cần thời gian để xử lý.</p>
    </center>
</div>

