<head>
    <title>Warning</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <script type="text/javascript" async="" src="http://www.google-analytics.com/ga.js"></script>
    <script type="text/javascript">
        //<![CDATA[
        var _gaq = _gaq || [];

        _gaq.push(['_setAccount', 'UA-75806361-1']);
        _gaq.push (['_gat._anonymizeIp']);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

        //]]>
    </script>
</head>

<body style="background: rgb(237, 240, 238) none repeat scroll 0% 0%;" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<!-- Save for Web Slices (notification_login.psd) -->
<div>
    <div style="text-align: center;
padding-top: 5%;">
        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/default/gcafe/images/gcafeshop_logo.png'; ?>"  alt=""></td>
    </div>
    <div style="text-align: center;
padding-top: 30px;">
        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/default/gcafe/images/notification_login_11.png'; ?>"  alt=""></td>
    </div>
</div>
<div style="width: 100%;
background: rgb(0, 0, 0) none repeat scroll 0% 0%;
color: white;
height: 40px;
text-align: center;
padding-top: 10px;
margin-top: 100px;
position: absolute;
bottom: 0px;">
	<span style="color: white;
text-align: center;">Copyright @GcafeShop 2016</span>
</div>
</body>
