<?php
/**
 * Created by PhpStorm.
 * User: Teko
 * Date: 7/12/2017
 * Time: 6:56 PM
 */
?>

<div class="breadcrumbs no-display">
    <ul>
        <div class="tekshop-cat-header-breadcrumbs">
            <div class="tekshop-cat-header-img">
                <img src="<?php echo $this->getSkinUrl('images/header-icon.png') ?>"/>
            </div>
            <div class="tekshop-breadcrumb-header">
                <li>
                    <a href="<?php echo $this->getUrl() ?>"
                       title="Trang chủ">Trang chủ</a>
                    <span>/ </span>
                    <strong>Xây dựng cấu hình</strong>
                </li>
            </div>
        </div>
    </ul>
</div>

<div class="bp-block">

    <div class="row mt-40">
        <div class="col-md-6 pl-15 lh-35 bp-title">
            CẤU HÌNH ĐÃ XÂY DỰNG
        </div>
        <div class="col-md-6 a-right">
            <button type="button" class="btn btn-warning bp-add-to-cart-btn" onclick="addToCartBuildPC()">
                Thêm vào giỏ hàng&nbsp;
                <i class="fa fa-shopping-cart"></i>
            </button>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 bp-selected-products no-padding">
            <div class="col-md-12 bp-selected-item">
                <div class="col-md-2 a-center no-padding">
                    <img src="http://tekshop.vn/media/catalog/product/cache/20/small_image/300x300/9df78eab33525d08d6e5fb8d27136e95/1/_/1_2_1_1.jpg"
                         alt="Chuột chơi game Tt eSports Azurues Mini"
                         title="Chuột chơi game Tt eSports Azurues Mini"
                         width="150"
                         height="150"
                    />
                </div>
                <div class="col-md-8">
                    <div class="bp-product-name">
                        Bo mạch chủ GIGABYTE Aorus Z270X - Gaming 7 Socket 1151 DDR4 Intel Z270
                    </div>
                    <div class="bp-product-old-price">
                        9.069.000 đ
                    </div>
                    <div class="bp-product-regular-price">
                        7.069.000 đ
                    </div>
                </div>
                <div class="col-md-2 a-right no-padding">
                    <button type="button" class="btn btn-info bp-table-btn bp-change-btn" data-toggle="modal" data-target="#changeProductModal">
                        Thay đổi
                    </button>
                </div>
            </div>
            <div class="col-md-12 bp-selected-item">
                <div class="col-md-2 a-center no-padding">
                    <img src="http://tekshop.vn/media/catalog/product/cache/20/small_image/300x300/9df78eab33525d08d6e5fb8d27136e95/1/_/1_2_1_1.jpg"
                         alt="Chuột chơi game Tt eSports Azurues Mini"
                         title="Chuột chơi game Tt eSports Azurues Mini"
                         width="150"
                         height="150"
                    />
                </div>
                <div class="col-md-8">
                    <div class="bp-product-name">
                        Bo mạch chủ GIGABYTE Aorus Z270X - Gaming 7 Socket 1151 DDR4 Intel Z270
                    </div>
                    <div class="bp-product-old-price">
                        9.069.000 đ
                    </div>
                    <div class="bp-product-regular-price">
                        7.069.000 đ
                    </div>
                </div>
                <div class="col-md-2 a-right no-padding">
                    <button type="button" class="btn btn-info bp-table-btn bp-change-btn" data-toggle="modal" data-target="#changeProductModal">
                        Thay đổi
                    </button>
                </div>
            </div>
            <div class="col-md-12 bp-selected-item">
                <div class="col-md-2 a-center no-padding">
                    <img src="http://tekshop.vn/media/catalog/product/cache/20/small_image/300x300/9df78eab33525d08d6e5fb8d27136e95/1/_/1_2_1_1.jpg"
                         alt="Chuột chơi game Tt eSports Azurues Mini"
                         title="Chuột chơi game Tt eSports Azurues Mini"
                         width="150"
                         height="150"
                    />
                </div>
                <div class="col-md-8">
                    <div class="bp-product-name">
                        Bo mạch chủ GIGABYTE Aorus Z270X - Gaming 7 Socket 1151 DDR4 Intel Z270
                    </div>
                    <div class="bp-product-old-price">
                        9.069.000 đ
                    </div>
                    <div class="bp-product-regular-price">
                        7.069.000 đ
                    </div>
                </div>
                <div class="col-md-2 a-right no-padding">
                    <button type="button" class="btn btn-info bp-table-btn bp-change-btn" data-toggle="modal" data-target="#changeProductModal">
                        Thay đổi
                    </button>
                </div>
            </div>
            <div class="col-md-12 bp-selected-item">
                <div class="col-md-2 a-center no-padding">
                    <img src="http://tekshop.vn/media/catalog/product/cache/20/small_image/300x300/9df78eab33525d08d6e5fb8d27136e95/1/_/1_2_1_1.jpg"
                         alt="Chuột chơi game Tt eSports Azurues Mini"
                         title="Chuột chơi game Tt eSports Azurues Mini"
                         width="150"
                         height="150"
                    />
                </div>
                <div class="col-md-8">
                    <div class="bp-product-name">
                        Bo mạch chủ GIGABYTE Aorus Z270X - Gaming 7 Socket 1151 DDR4 Intel Z270
                    </div>
                    <div class="bp-product-old-price">
                        9.069.000 đ
                    </div>
                    <div class="bp-product-regular-price">
                        7.069.000 đ
                    </div>
                </div>
                <div class="col-md-2 a-right no-padding">
                    <button type="button" class="btn btn-info bp-table-btn bp-change-btn" data-toggle="modal" data-target="#changeProductModal">
                        Thay đổi
                    </button>
                </div>
            </div>
            <div class="col-md-12 bp-selected-item">
                <div class="col-md-2 a-center no-padding">
                    <img src="http://tekshop.vn/media/catalog/product/cache/20/small_image/300x300/9df78eab33525d08d6e5fb8d27136e95/1/_/1_2_1_1.jpg"
                         alt="Chuột chơi game Tt eSports Azurues Mini"
                         title="Chuột chơi game Tt eSports Azurues Mini"
                         width="150"
                         height="150"
                    />
                </div>
                <div class="col-md-8">
                    <div class="bp-product-name">
                        Bo mạch chủ GIGABYTE Aorus Z270X - Gaming 7 Socket 1151 DDR4 Intel Z270
                    </div>
                    <div class="bp-product-old-price">
                        9.069.000 đ
                    </div>
                    <div class="bp-product-regular-price">
                        7.069.000 đ
                    </div>
                </div>
                <div class="col-md-2 a-right no-padding">
                    <button type="button" class="btn btn-info bp-table-btn bp-change-btn" data-toggle="modal" data-target="#changeProductModal">
                        Thay đổi
                    </button>
                </div>
            </div>
            <div class="col-md-12 bp-selected-item">
                <div class="col-md-2 a-center no-padding">
                    <img src="http://tekshop.vn/media/catalog/product/cache/20/small_image/300x300/9df78eab33525d08d6e5fb8d27136e95/1/_/1_2_1_1.jpg"
                         alt="Chuột chơi game Tt eSports Azurues Mini"
                         title="Chuột chơi game Tt eSports Azurues Mini"
                         width="150"
                         height="150"
                    />
                </div>
                <div class="col-md-8">
                    <div class="bp-product-name">
                        Bo mạch chủ GIGABYTE Aorus Z270X - Gaming 7 Socket 1151 DDR4 Intel Z270
                    </div>
                    <div class="bp-product-old-price">
                        9.069.000 đ
                    </div>
                    <div class="bp-product-regular-price">
                        7.069.000 đ
                    </div>
                </div>
                <div class="col-md-2 a-right no-padding">
                    <button type="button" class="btn btn-info bp-table-btn bp-change-btn" data-toggle="modal" data-target="#changeProductModal">
                        Thay đổi
                    </button>
                </div>
            </div>
            <div class="col-md-12 bp-selected-item">
                <div class="col-md-2 a-center no-padding">
                    <img src="http://tekshop.vn/media/catalog/product/cache/20/small_image/300x300/9df78eab33525d08d6e5fb8d27136e95/1/_/1_2_1_1.jpg"
                         alt="Chuột chơi game Tt eSports Azurues Mini"
                         title="Chuột chơi game Tt eSports Azurues Mini"
                         width="150"
                         height="150"
                    />
                </div>
                <div class="col-md-8">
                    <div class="bp-product-name">
                        Bo mạch chủ GIGABYTE Aorus Z270X - Gaming 7 Socket 1151 DDR4 Intel Z270
                    </div>
                    <div class="bp-product-old-price">
                        9.069.000 đ
                    </div>
                    <div class="bp-product-regular-price">
                        7.069.000 đ
                    </div>
                </div>
                <div class="col-md-2 a-right no-padding">
                    <button type="button" class="btn btn-info bp-table-btn bp-change-btn" data-toggle="modal" data-target="#changeProductModal">
                        Thay đổi
                    </button>
                </div>
            </div>
            <div class="col-md-12 bp-selected-item">
                <div class="col-md-2 a-center no-padding">
                    <img src="http://tekshop.vn/media/catalog/product/cache/20/small_image/300x300/9df78eab33525d08d6e5fb8d27136e95/1/_/1_2_1_1.jpg"
                         alt="Chuột chơi game Tt eSports Azurues Mini"
                         title="Chuột chơi game Tt eSports Azurues Mini"
                         width="150"
                         height="150"
                    />
                </div>
                <div class="col-md-8">
                    <div class="bp-product-name">
                        Bo mạch chủ GIGABYTE Aorus Z270X - Gaming 7 Socket 1151 DDR4 Intel Z270
                    </div>
                    <div class="bp-product-old-price">
                        9.069.000 đ
                    </div>
                    <div class="bp-product-regular-price">
                        7.069.000 đ
                    </div>
                </div>
                <div class="col-md-2 a-right no-padding">
                    <button type="button" class="btn btn-info bp-table-btn bp-change-btn" data-toggle="modal" data-target="#changeProductModal">
                        Thay đổi
                    </button>
                </div>
            </div>
            <div class="col-md-12 bp-selected-item">
                <div class="col-md-2 a-center no-padding">
                    <img src="http://tekshop.vn/media/catalog/product/cache/20/small_image/300x300/9df78eab33525d08d6e5fb8d27136e95/1/_/1_2_1_1.jpg"
                         alt="Chuột chơi game Tt eSports Azurues Mini"
                         title="Chuột chơi game Tt eSports Azurues Mini"
                         width="150"
                         height="150"
                    />
                </div>
                <div class="col-md-8">
                    <div class="bp-product-name">
                        Bo mạch chủ GIGABYTE Aorus Z270X - Gaming 7 Socket 1151 DDR4 Intel Z270
                    </div>
                    <div class="bp-product-old-price">
                        9.069.000 đ
                    </div>
                    <div class="bp-product-regular-price">
                        7.069.000 đ
                    </div>
                </div>
                <div class="col-md-2 a-right no-padding">
                    <button type="button" class="btn btn-info bp-table-btn bp-change-btn" data-toggle="modal" data-target="#changeProductModal">
                        Thay đổi
                    </button>
                </div>
            </div>
            <div class="col-md-12 bp-selected-item">
                <div class="col-md-2 a-center no-padding">
                    <img src="http://tekshop.vn/media/catalog/product/cache/20/small_image/300x300/9df78eab33525d08d6e5fb8d27136e95/1/_/1_2_1_1.jpg"
                         alt="Chuột chơi game Tt eSports Azurues Mini"
                         title="Chuột chơi game Tt eSports Azurues Mini"
                         width="150"
                         height="150"
                    />
                </div>
                <div class="col-md-8">
                    <div class="bp-product-name">
                        Bo mạch chủ GIGABYTE Aorus Z270X - Gaming 7 Socket 1151 DDR4 Intel Z270
                    </div>
                    <div class="bp-product-old-price">
                        9.069.000 đ
                    </div>
                    <div class="bp-product-regular-price">
                        7.069.000 đ
                    </div>
                </div>
                <div class="col-md-2 a-right no-padding">
                    <button type="button" class="btn btn-info bp-table-btn bp-change-btn" data-toggle="modal" data-target="#changeProductModal">
                        Thay đổi
                    </button>
                </div>
            </div>
            <div class="col-md-12 bp-selected-item">
                <div class="col-md-2 a-center no-padding">
                    <img src="http://tekshop.vn/media/catalog/product/cache/20/small_image/300x300/9df78eab33525d08d6e5fb8d27136e95/1/_/1_2_1_1.jpg"
                         alt="Chuột chơi game Tt eSports Azurues Mini"
                         title="Chuột chơi game Tt eSports Azurues Mini"
                         width="150"
                         height="150"
                    />
                </div>
                <div class="col-md-8">
                    <div class="bp-product-name">
                        Bo mạch chủ GIGABYTE Aorus Z270X - Gaming 7 Socket 1151 DDR4 Intel Z270
                    </div>
                    <div class="bp-product-old-price">
                        9.069.000 đ
                    </div>
                    <div class="bp-product-regular-price">
                        7.069.000 đ
                    </div>
                </div>
                <div class="col-md-2 a-right no-padding">
                    <button type="button" class="btn btn-info bp-table-btn bp-change-btn" data-toggle="modal" data-target="#changeProductModal">
                        Thay đổi
                    </button>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 mb-40 a-right">
            <button type="button" class="btn btn-success bp-success-btn mr-20" onclick="addToCartBuildPC()">
                Tải file Excel cấu hình&nbsp;
                <i class="fa fa-file-excel-o"></i>
            </button>
            <button type="button" class="btn btn-success bp-success-btn mr-20" onclick="addToCartBuildPC()">
                Tải file ảnh cấu hình&nbsp;
                <i class="fa fa-picture-o"></i>
            </button>
            <button type="button" class="btn btn-success bp-success-btn mr-20" onclick="addToCartBuildPC()">
                Chia sẻ cấu hình&nbsp;
                <i class="fa fa-facebook-official "></i>
            </button>
            <button type="button" class="btn btn-warning bp-add-to-cart-btn" onclick="addToCartBuildPC()">
                Thêm vào giỏ hàng&nbsp;
                <i class="fa fa-shopping-cart"></i>
            </button>
        </div>
    </div>

    <!-- Modal -->
    <div id="changeProductModal" class="modal fade" role="dialog">
        <div class="modal-dialog bp-modal-dialog">

            <!-- Modal content-->
            <div class="modal-content bp-modal-content">
                <div class="modal-header bp-modal-header">
                    <div class="row">
                        <div class="col-md-3 bp-modal-title">
                            Chọn linh kiện
                        </div>
                        <div class="col-md-6">
                            <input type="text" class="bp-search-input" placeholder="Tìm kiếm sản phẩm"/>
                            <i class="fa fa-search bp-search-icon"></i>
                        </div>
                        <div class="col-md-3 a-right">
                            <button type="button" class="btn bp-sort-btn">Sắp xếp sản phẩm theo</button>
                        </div>
                    </div>
                </div>
                <div class="modal-body bp-modal-body">
                    <div class="row">
                        <div class="col-md-3 bp-filter-block">
                            <h1>Bộ lọc</h1>
                        </div>
                        <div class="col-md-9">

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<script>
    var $j = jQuery.noConflict();

    function addToCartBuildPC() {
        console.log('add to cart');
    }
</script>
