<?php
/**
 * @category    TheExtensionLab
 * @package     TheExtensionLab_MegaMenu
 * @copyright   Copyright (c) 2015 TheExtensionLab (http://www.theextensionlab.com)
 * @license     Open Software License (OSL 3.0)
 * @author      James Anelay @ TheExtensionLab <james@theextensionlab.com>
 */

/** @var Varien_Data_Tree_Node $menuTree */
/** @var string $childrenWrapClass */
?>
<?php $version = Teko::getSaleCenterVersion(); ?>
<?php $children = $menuTree->getChildren();?>
<?php foreach($children as $child):?>

    <?php $cat = Mage::getModel('catalog/category')->load(preg_replace('/[^0-9]/', '', $child->getId())); ?>
    <?php $catIconName = $cat->getDescription(); ?>

    <?php if($child->getIncludeInMenu()):?>
        <?php $this->setCategoryData($child,$menuTree->getLevel());?>
        <li class="cat-menu-item">
            <?php if(!$this->_isCategoryPlaceholder($child)):?>
                <img class="cat-icon-img cat-icon-img-original"
                     src="<?php echo $this->getSkinUrl('images/menu-icon/') . $catIconName . '.svg' ?><?php echo "?v=" . $version ?>"/>
                <img class="cat-icon-img cat-icon-img-hover"
                     src="<?php echo $this->getSkinUrl('images/menu-icon/') . $catIconName . '_White.svg' ?><?php echo "?v=" . $version ?>"/>
                <a href="<?php echo $child->getUrl();?>" class="<?php echo $this->getCategoryLiClass($child)?> cat-menu-item-name">
                    <span><?php echo $this->escapeHtml($child->getName())?></span>
                </a>
            <?php else:?>
                <span class="<?php echo $this->getCategoryLiClass($child)?>"><?php echo $this->escapeHtml($child->getName())?></span>
            <?php endif;?>

            <?php if(!empty($childrenWrapClass)) :?>
                <div class="<?php echo $childrenWrapClass?>">
            <?php endif;?>

            <?php if ($child->getHasDropDownContent()):?>

                <?php $inlineStyle = $this->getDropDownInlineStyle($child);?>

                <div class="<?php echo $this->getMenuDropDownTypeClass($child);?>" <?php if(!empty($inlineStyle)): echo 'style="'.$inlineStyle.'"'; endif; ?>>
                    <?php foreach($child->getColumns() as $column):?>
                        <?php if(!empty($column['content']) && $column['col_width'] != 0):?>
                            <div class="column xlab_column_<?php echo $column['col_width'];?>">
                                <?php echo $column['content'];?>
                            </div>
                        <?php endif;?>
                    <?php endforeach;?>
                </div>
            <?php endif;?>

            <?php if(!empty($childrenWrapClass)) :?>
                </div>
            <?php endif;?>

        </li>
    <?php endif;?>
<?php endforeach;?>

<script type="text/javascript">
    var $j = jQuery.noConflict();
    $j(document).ready(function(){
       console.log(<?php echo $children; ?>);
       console.log('abc');
    });
</script>
