<head>
    <title>Warning</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>

<body style="background: rgb(237, 240, 238) none repeat scroll 0% 0%;" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<!-- Save for Web Slices (notification_login.psd) -->
<div>
    <div style="text-align: center;
padding-top: 5%;">
        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/default/f002/images/notification_login_05.png'; ?>"  alt=""></td>
    </div>
    <div style="text-align: center;
padding-top: 30px;">
        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/default/f002/images/notification_login_11.png'; ?>"  alt=""></td>
    </div>
</div>
<div style="width: 100%;
background: rgb(0, 0, 0) none repeat scroll 0% 0%;
color: white;
height: 40px;
text-align: center;
padding-top: 10px;
margin-top: 100px;
position: absolute;
bottom: 0px;">
	<span style="color: white;
text-align: center;">Copyright @Gcafeshop 2016</span>
</div>
</body>
