<?php
$_categories = Mage::helper('catalog/category')->getStoreCategories();
?>
<?php $version = Teko::getSaleCenterVersion(); ?>
<?php if (count($_categories) > 0): ?>
    <?php foreach ($_categories as $_category): ?>
        <?php $_category = Mage::getModel('catalog/category')->load($_category->getId()); ?>
        <div class="cat-menu-item" onclick="window.location.href = '<?php echo $_category->getUrl(); ?>';">
            <?php $catIconName = $_category->getDescription(); ?>
            <img class="cat-icon-img cat-icon-img-original"
                 src="<?php echo $this->getSkinUrl('images/menu-icon/') . $catIconName . '.svg' ?><?php echo "?v=" . $version ?>"/>
            <img class="cat-icon-img cat-icon-img-hover"
                 src="<?php echo $this->getSkinUrl('images/menu-icon/') . $catIconName . '_White.svg' ?><?php echo "?v=" . $version ?>"/>
            <a class="cat-menu-item-name"
               href="<?php echo $_category->getUrl(); ?>"><?php echo $_category->getName(); ?></a>
            <?php $_subcategories = $_category->getChildrenCategories(); ?>
            <?php if (count($_subcategories) > 0): ?>
                <i class="fa fa-chevron-right chevron-icon"></i>
                <div class="sub-cat-menu">
                    <?php foreach ($_subcategories as $_subcategory): ?>
                        <div class="sub-cat-item">
                            <a class="sub-cat-item-name"
                               href="<?php echo $_subcategory->getUrl(); ?>"><?php echo $_subcategory->getName(); ?></a>
                            <?php $_l3subcategories = $_subcategory->getChildrenCategories(); ?>
                            <?php if (count($_l3subcategories) > 0): ?>
                                <?php foreach ($_l3subcategories as $_l3subcategory): ?>
                                    <a class="sub-cat-item-filter"
                                       href="<?php echo $_l3subcategory->getUrl(); ?>"><?php echo $_l3subcategory->getName(); ?></a>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </div>
                    <?php endforeach; ?>
                    <div class="cat-banner-block">
                        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('cat-banner-' . $_category->getId())->toHtml(); ?>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
