<?php $_productImpressions = []; ?>
<?php
$_recentlyProducts = Mage::getSingleton('Mage_Reports_Block_Product_Viewed')->getItemsCollection()
    ->addAttributeToFilter('instock', array('in' => array(1, 6)));;
?>
<?php if (count($_recentlyProducts) > 0): ?>
    <?php
    $tagProduct = Mage::getModel('tag/tag_relation')
        ->setTagId(1)// Bao ke gia
        ->setStoreId((Mage::app()->getStore()->getId()))
        ->getProductIds();
    $tagOnlinePaymentIds = Mage::getModel('tag/tag_relation')
        ->setTagId(3)// Giam gia thanh toan online
        ->setStoreId(Mage::app()->getStore()->getId())
        ->getProductIds();
    ?>
    <div class="col-md-10 col-md-offset-1 recently-viewed-block-responsive">
        <div class="recently-viewed-block-border-top"></div>
        <div class="recently-viewed-title">Sản phẩm xem gần đây</div>
        <div class="row recently-viewed-products">
            <?php foreach ($_recentlyProducts as $_product): ?>
                <?php
                $_productObj = new stdClass();
                $_productObj->name = $this->escapeHtml($_product->getName());
                $_productObj->id = intval($_product->getId());
                $_productObj->price = intval($_product->getFinalPrice());
                $_productObj->list = 'Category Page';
                $_productImpressions[] = $_productObj;
                ?>
                <?php
                $oldPrice = $_product->getPrice();
                $finalPrice = $_product->getFinalPrice();
                ?>
                <div class="col-md-15 col-sm-15">
                    <?php if (in_array((string)$_product->getId(), $tagProduct)): ?>
                        <img class="list-tag"
                             src='<?php echo $this->getSkinUrl('images/tag.png') ?>'/>
                    <?php endif; ?>
                    <a href="<?php echo $_product->getProductFullUrl(); ?>"
                       onclick="trackProductClicks(this);"
                       data-id="<?php echo $_product->getId(); ?>"
                       data-name="<?php echo $this->escapeHtml($_product->getName()); ?>"
                       data-price="<?php echo $_product->getFinalPrice(); ?>"
                       title="<?php echo $this->escapeHtml($_product->getName()); ?>">
                        <img class="recently-viewed-img"
                             src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300, 300); ?>"/>
                    </a>

                    <div class="product-discount">
                        <?php if ($oldPrice != $finalPrice) : ?>
                            <div class="recently-viewed-old-price">
                                <?php echo number_format($oldPrice, 0, ",", ".") . " ₫"; ?>
                            </div>
                            <div class="recently-viewed-discount">
                                <span class="discount-number">
                                    (-<?php echo number_format(($oldPrice - $finalPrice) / $oldPrice * 100, 0) . "%" ?>
                                    )
                                </span>
                            </div>
                        <?php endif; ?>
                    </div>
                    <div class="recently-viewed-final-price">
                        <?php echo number_format($finalPrice, 0, ",", ".") . " ₫"; ?>
                    </div>
                    <div class="tag-online-payment">
                        <?php if (in_array($_product->getId(), $tagOnlinePaymentIds)): ?>
                            <img src="<?php echo $this->getSkinUrl('images/icon_Notify.svg'); ?>"/>
                            Chỉ áp dụng đặt hàng online
                        <?php endif; ?>
                    </div>
                    <a class="recently-viewed-name"
                       href="<?php echo $_product->getProductFullUrl(); ?>"
                       onclick="trackProductClicks(this);"
                       data-id="<?php echo $_product->getId(); ?>"
                       data-name="<?php echo $this->escapeHtml($_product->getName()); ?>"
                       data-price="<?php echo $_product->getFinalPrice(); ?>"
                       title="<?php echo $this->escapeHtml($_product->getName()); ?>">
                        <?php echo $_product->getName(); ?>
                    </a>
                </div>
            <?php endforeach; ?>
        </div>
    </div>

    <script type="text/javascript">
        /** Track product impressions **/
        var productImpressions = <?php echo json_encode($_productImpressions); ?>;
        dataLayer.push({
            'event': 'productImpressions',
            'ecommerce': {
                'currencyCode': 'VND',
                'impressions': productImpressions
            }
        });
    </script>
<?php endif; ?>
