<?php $_productImpressions = []; ?>
<?php
$_recentlyProducts = Mage::getSingleton('Mage_Reports_Block_Product_Viewed')->getItemsCollection()
    ->addAttributeToFilter('instock', array('in' => array(1, 6)));
?>
<?php if (count($_recentlyProducts) > 0): ?>
    <?php
    $tagProduct = Mage::getModel('tag/tag_relation')
        ->setTagId(1)// Bao ke gia
        ->setStoreId((Mage::app()->getStore()->getId()))
        ->getProductIds();
    $tagOnlinePaymentIds = Mage::getModel('tag/tag_relation')
        ->setTagId(3)// Giam gia thanh toan online
        ->setStoreId(Mage::app()->getStore()->getId())
        ->getProductIds();
    ?>
    <div class="row recently-viewed-block">
        <div class="col-md-10 col-md-offset-1 recently-viewed-block-responsive">
            <div class="cat-name">Sản phẩm xem gần đây</div>
            <div class="row recently-viewed-products">
                <?php foreach ($_recentlyProducts as $_product): ?>
                    <?php
                    $_productObj = new stdClass();
                    $_productObj->name = $this->escapeHtml($_product->getName());
                    $_productObj->id = intval($_product->getId());
                    $_productObj->price = intval($_product->getFinalPrice());
                    $_productObj->list = 'Home Page';
                    $_productImpressions[] = $_productObj;
                    ?>
                    <?php
                    $oldPrice = $_product->getPrice();
                    $finalPrice = $_product->getFinalPrice();
                    ?>
                    <!-- Get promotion info-->
                    <?php
                    $includedProduct = json_decode($this->helper('catalog/output')->productAttribute($_product, nl2br($_product->getPromotionInfo()), 'promotion_info'));
                    $includedProductIds = [];
                    $includedProductQty = [];
                    if ($includedProduct) {
                        $includedProductIds = json_decode($this->helper('catalog/output')->productAttribute($_product, nl2br($_product->getPromotionInfo()), 'promotion_info'))->promotion_ids;
                        $includedProductQty = json_decode($this->helper('catalog/output')->productAttribute($_product, nl2br($_product->getPromotionInfo()), 'promotion_info'))->promotion_qty;
                    }
                    $promotionInfoHtml = '<b>Tặng kèm:</b>';
                    ?>
                    <?php if (count($includedProductIds) > 0 && count($includedProductQty) > 0): ?>
                        <?php foreach ($includedProductIds as $key => $id): ?>
                            <?php
                            $_includedProduct = Mage::getModel('catalog/product')->load($id);
                            $promotionInfoHtml .= '</br>- ' . $includedProductQty[$key] . ' ' . $this->escapeHtml($_includedProduct->getName()) . '';
                            ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <!-- End get promotion info-->
                    <div class="col-md-15 col-sm-15">
                        <div class="product-content">
                            <?php if (in_array((string)$_product->getId(), $tagProduct)): ?>
                                <img class="list-tag"
                                     src='<?php echo $this->getSkinUrl('images/tag.png') ?>'/>
                            <?php endif; ?>
                            <a href="<?php echo $_product->getProductFullUrl(); ?>"
                               onclick="trackProductClicks(this);"
                               data-id="<?php echo $_product->getId(); ?>"
                               data-name="<?php echo $this->escapeHtml($_product->getName()); ?>"
                               data-price="<?php echo $_product->getFinalPrice(); ?>"
                            >
                                <img class="product-img lazy" src="" alt=""
                                     data-src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300, 300); ?>"
                                     data-product-name="<?php echo $this->escapeHtml($_product->getName()); ?>"
                                     data-product-price="<?php echo number_format($_product->getFinalPrice(), 0, ",", ".") . " ₫"; ?>"
                                     data-product-desc="<?php echo $this->escapeHtml($this->helper('catalog/output')->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description')); ?>"
                                />
                            </a>
                            <div class="product-info">
                                <div class="product-discount">
                                    <?php if ($oldPrice != $finalPrice) : ?>
                                        <div class="old-price">
                                            <?php echo number_format($oldPrice, 0, ",", ".") . " ₫"; ?>
                                        </div>
                                        <div class="discount">
                                            <span class="discount-number">
                                                (-<?php echo number_format(($oldPrice - $finalPrice) / $oldPrice * 100, 0) . "%" ?>
                                                )
                                            </span>
                                        </div>
                                    <?php endif; ?>
                                </div>
                                <div class="final-price">
                                    <?php echo number_format($finalPrice, 0, ",", ".") . " ₫"; ?>
                                </div>
                                <div class="tag-online-payment">
                                    <?php if (in_array($_product->getId(), $tagOnlinePaymentIds)): ?>
                                        <img src="<?php echo $this->getSkinUrl('images/icon_Notify.svg'); ?>"/>
                                        Chỉ áp dụng đặt hàng online
                                    <?php endif; ?>
                                </div>
                                <?php if (count($includedProductIds) > 0 && count($includedProductQty) > 0): ?>
                                    <img class="product-gift-icon" data-toggle="tooltip"
                                         title="<?php echo $promotionInfoHtml; ?>"
                                         src="<?php echo $this->getSkinUrl('images/icon_Gift.svg'); ?>"/>
                                <?php endif; ?>
                                <a class="product-name" onclick="trackProductClicks(this);"
                                   data-id="<?php echo $_product->getId(); ?>"
                                   data-name="<?php echo $this->escapeHtml($_product->getName()); ?>"
                                   data-price="<?php echo $_product->getFinalPrice(); ?>"
                                   href="<?php echo $_product->getProductFullUrl(); ?>"
                                   title="<?php echo $this->escapeHtml($_product->getName()); ?>">
                                    <?php echo $this->escapeHtml($_product->getName()); ?>
                                </a>
                            </div>
                            <div class="product-btn">
                                <?php
                                $addToCartUrl = ($_product->getTypeId() == 'simple') ? Mage::helper('checkout/cart')->getAddUrl($_product) : $_product->getProductFullUrl();
                                ?>
                                <button type="button"
                                        class="add-to-cart-btn add-to-cart-from-list-btn"
                                        data-product-name="<?php echo $this->escapeHtml($_product->getName()); ?>"
                                        data-product-id="<?php echo intval($_product->getId()); ?>"
                                        data-product-price="<?php echo intval($_product->getFinalPrice()); ?>"
                                        data-product-type="<?php echo $_product->getTypeId(); ?>"
                                        data-add-to-cart-url="<?php echo $addToCartUrl; ?>"
                                >
                                    Thêm vào giỏ hàng
                                    <img class="add-to-cart-from-list-icon hidden-1200"
                                         src="<?php echo $this->getSkinUrl('images/icon_ShoppingCart2.svg'); ?>"/>
                                    <img class="add-to-cart-from-list-ajax-loader hidden"
                                         src="<?php echo $this->getSkinUrl('images/ajax-loader-white.gif'); ?>"/>
                                </button>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        /** Track product impressions **/
        var productImpressions = <?php echo json_encode($_productImpressions); ?>;
        dataLayer.push({
            'event': 'productImpressions',
            'ecommerce': {
                'currencyCode': 'VND',
                'impressions': productImpressions
            }
        });
    </script>
<?php endif; ?>
