<?php $_filters = $this->getActiveFilters() ?>
<?php if (!empty($_filters)): ?>
    <div class="row state-horizontal-wrapper hidden-mobile">
        <?php
        $filterGroup = array();
        foreach ($_filters as $_filter) {
            if (!isset($filterGroup[$_filter->getName()])) {
                $filterGroup[$_filter->getName()] = array();
            }
            array_push($filterGroup[$_filter->getName()], (object)[
                'label' => $this->escapeHtml($_filter->getLabel()),
                'removeUrl' => $_filter->getRemoveUrl(),
            ]);
        }
        ?>
        <div class="col-xs-12">
            <span class="state-title hidden-xs">Bạn đang lọc theo </span>
            <?php if (count($filterGroup) > 0): ?>
                <?php foreach ($filterGroup as $key => $group): ?>
                    <span class="filter-group">
                        <span class="filter-group-name"><?php echo $key == 'Category' ? 'Danh mục' : $key ?>: </span>
                        <?php foreach ($group as $filter): ?>
                            <span class="filter-group-item" onclick="ajaxFilter('<?php echo $filter->removeUrl ?>')">
                                <?php echo $filter->label ?>
                                <i class="fa fa-times"></i>
                            </span>
                        <?php endforeach; ?>
                    </span>
                <?php endforeach; ?>
            <?php endif; ?>
            <span class="filter-reset" title="Xóa bộ lọc" onclick="ajaxFilter('<?php echo $this->getClearUrl() ?>')">
            Xóa bộ lọc
        </span>
        </div>
    </div>
<?php endif; ?>
