<?php
/**
 * @var Ved_Tracking_Block_Order $this
 * @var Mage_Sales_Model_Order $order
 */
?>
<!--iconMoon CSS-->
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('lib/icomoon.css'); ?>"/>
<!--Tracking Order CSS-->
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('lib/trackingOrder.css'); ?>"/>
<script>
    dataLayer = [];
</script>

<?php $orders = Mage::registry('orders'); ?>
<?php $phone_number = Mage::registry('phone_number'); ?>
<?php
$countCompletedOrder = 0;
$totalPayment = 0;
foreach ($orders as $order) {
    if ($order->getStatus() == 'delivered' || $order->getState() == 'complete') {
        $countCompletedOrder++;
        $totalPayment += $order->getGrandTotal();
    }
}
?>
<div class="content">

    <!--Breadcrumb-->
    <div class="row tek-breadcrumb">
        <div class="col-md-10 col-md-offset-1 content-section">
            <div class="tek-breadcrumb-content" style="padding: 6px 0 5px 0;"></div>
            <div class="tek-breadcrumb-main">
                <span>Kiểm tra đơn hàng</span>
            </div>
        </div>
    </div>
    <!--End Breadcrumb-->

    <div class="row list-block tracking-content">
        <div class="col-md-10 col-md-offset-1 content-section">
            <?php $first_order = $orders->getFirstItem(); ?>
            <?php if ($first_order->getShippingAddress()): ?>
                <?php
                $order_state = $first_order->getState();
                $order_status = $first_order->getStatus()
                ?>
                <div class="col-md-4 new-track-orders">
                    <div class="new-order-title">
                        ĐƠN HÀNG MỚI NHẤT
                        <div class="pt-10">
                            <div class="tracking-total-info">
                                Số đơn hoàn thành: <?php echo $countCompletedOrder ?>
                            </div>
                            <div class="tracking-total-info">
                                Tổng tiền thanh
                                toán: <?php echo Mage::helper('core')->currency($totalPayment, true, false) ?>
                            </div>
                        </div>
                    </div>
                    <div class="search-list-orders">
                        <form id="search-order-form"
                              action="<?php echo $this->getUrl('tracking/order/search') ?>"
                              method="post">
                            <input type="hidden" name="phone_number" value="<?php echo $phone_number ?>">
                            <input type="number"
                                   id="search-track-order"
                                   placeholder="Tìm theo mã đơn hàng" name="search_key_order_id"
                                   onkeyup="doSearchOrder()"/>
                            <span class="search-order-loading hidden" title="Đang tải"><img
                                        src="<?php echo $this->getSkinUrl('images/ajax-loader-new.gif') ?>"
                                        width="60" height="60"/></span>
                        </form>
                        <div class="list-orders">
                            <?php foreach ($orders as $order): ?>
                                <div id="track-order-item-<?php echo (string)$order->getIncrementId(); ?>"
                                     data-id="<?php echo (string)$order->getIncrementId(); ?>"
                                     class="row track-order-item <?php if ($order->getIncrementId() == $first_order->getIncrementId()): ?>track-order-item-active<?php endif; ?>"
                                     onclick="checkOrderDetail(this)">
                                    <div class="col-md-4 col-xs-4 track-order-id">
                                        <b><?php echo (string)$order->getIncrementId(); ?></b></div>


                                    <div class="col-md-4 col-xs-4 track-order-id">
                                        <?php echo date("d/m/Y", strtotime($order->getCreatedAtStoreDate())); ?>
                                    </div>
                                    <div class="col-md-4 col-xs-4"><?php echo $this->getStateName($order->getState(), $order->getStatus()) ?></div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
                <div class="col-md-8 track-order-content">
                    <span class="track-order-detail-loading hidden" title="Đang tải">
                        <img src="<?php echo $this->getSkinUrl('images/ajax-loader-new.gif') ?>" width="60"
                             height="60"/>
                    </span>
                    <div class="track-order-detail">
                        <?php
                        $shipping_address = $first_order->getShippingAddress();
                        $full_name = $shipping_address->getName();
                        $street = $shipping_address->getStreetFull();
                        $city = $shipping_address->getCity();
                        $region = $shipping_address->getRegion();
                        $telephone = $shipping_address->getTelephone();
                        $email = $shipping_address->getEmail();
                        $full_address = $street . ', ' . $city . ', ' . $region;
                        $total_free_item_price = 0;
                        ?>
                        <div class="track-order-title">THÔNG TIN ĐƠN HÀNG</div>
                        <div class="track-order-subtitle">
                            <span>MÃ ĐƠN HÀNG: <?php echo $first_order->getIncrementId(); ?></span>
                            <span>ĐẶT NGÀY: <?php echo date("d/m/Y H:i", strtotime($first_order->getCreatedAtStoreDate())); ?></span>
                        </div>
                        <div class="track-order-detail-panel">
                            <div class="row track-order-detail-header">
                                <div class="col-md-5 col-xs-12 order-header-block">
                                    <div><b>Địa chỉ: </b><?php echo $full_address ?></div>
                                    <hr class="hidden-md hidden-lg"/>
                                </div>
                                <div class="col-md-4 col-xs-6 order-header-block">
                                    <div>
                                        <b>Tên: </b><?php echo $full_name ?><br>
                                        <b>Điện thoại: </b><?php echo $telephone; ?>
                                    </div>
                                </div>
                                <div class="col-md-3 col-xs-6">
                                    <div>
                                        <b>Tình trạng: </b><?php echo $this->getStateName($order_state, $order_status) ?>
                                    </div>
                                </div>
                            </div>
                            <div class="row track-order-detail-status">

                                <div class="track-progress">
                                    <div class="circle <?php if ($order_state == 'canceled'): ?>canceled<?php else: ?>active<?php endif; ?>">
                                        <span class="label icon-delivery-package-opened"></span>
                                        <span class="title">Đang xử lý</span>
                                    </div>

                                    <span class="bar <?php if ($order_state == 'processing' || $order_state == 'complete'): ?>active<?php elseif ($order_state == 'canceled'): ?>canceled<?php endif; ?>"></span>

                                    <div class="circle <?php if ($order_state == 'processing' || $order_state == 'complete'): ?>active<?php elseif ($order_state == 'canceled'): ?>canceled<?php endif; ?>">
                                        <span class="label icon-delivery-truck"></span>
                                        <span class="title">Đang vận chuyển</span>

                                    </div>
                                    <span class="bar <?php if ($order_status == 'delivered' || $order_state == 'complete'): ?>active<?php elseif ($order_state == 'canceled'): ?>canceled<?php endif; ?>"></span>

                                    <div class="circle <?php if ($order_status == 'delivered' || $order_state == 'complete'): ?>active<?php elseif ($order_state == 'canceled'): ?>canceled<?php endif; ?>">
                                        <span class="label <?php if ($order_state == 'canceled'): ?>fa fa-icon fa-times<?php else: ?>icon-check<?php endif; ?>"></span>
                                        <span class="title"><?php if ($order_state == 'canceled'): ?>Đã hủy<?php else: ?>Hoàn tất<?php endif; ?></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row track-order-detail-items">
                                <div class="row track-order-item-title">Chi tiết đơn hàng:</div>
                                <div class="top-row track-order-top-row">
                                    <div class="col-md-8 col-xs-7 track-order-text-title">Chi tiết sản phẩm</div>
                                    <div class="col-md-2 col-xs-2 track-order-text-title text-center">Số lượng</div>
                                    <div class="col-md-2 col-xs-3 track-order-text-title text-right">Thành tiền</div>
                                </div>

                                <div class="mid-row track-order-mid-row no-padding-xs">
                                    <?php $_items = $first_order->getItemsCollection(); ?>
                                    <?php $_index = 0; ?>
                                    <?php $_count = $_items->count(); ?>
                                    <?php foreach ($_items as $_item): ?>
                                        <?php $total = $_item->getPrice() * $_item->getQtyOrdered(); ?>
                                        <?php $freeItem = unserialize($_item->getAdditionalData()); ?>
                                        <?php if ($_item->getParentItem()) continue; ?>
                                        <div class="col-md-8 col-xs-7 track-item-row no-padding-xs">
                                            <div class="col-md-4 col-sm-4 hidden-xs no-padding">
                                                <img src="<?php echo Mage::helper('catalog/image')->init($_item->getProduct(), 'small_image'); ?>"
                                                     width="100" height="100">
                                            </div>
                                            <div class="col-md-8 col-sm-8 col-xs-12 no-padding-xs">
                                                <a href="<?php echo $_item->getProduct()->getProductFullUrl() ?>"
                                                   class="order-item-name"><?php echo $_item->getName(); ?></a>
                                                <div class="col-md-12 col-xs-12 pt-5 pl-0">
                                                    <span class='free-item-number'><?php echo ($freeItem && isset($freeItem['parent'])) ? "(Sản phẩm khuyến mãi)" : ''; ?></span>
                                                </div>
                                                <div class="col-md-12 col-xs-12 pl-25">
                                                    <?php if (isset($_item->getProductOptions()['bundle_options'])): ?>
                                                        <?php $_options = $_item->getProductOptions()['bundle_options']; ?>
                                                        <dl class="item-options">
                                                            <?php foreach ($_options as $_option) : ?>
                                                                <dt><?php echo Mage::helper('core')->escapeHtml($_option['label'], null) ?></dt>
                                                                <dd>
                                                                    <?php foreach ($_option['value'] as $_option_value): ?>
                                                                        <?php echo $_option_value['title']; ?>
                                                                    <?php endforeach; ?>
                                                                </dd>
                                                            <?php endforeach; ?>
                                                        </dl>
                                                    <?php elseif (isset($_item->getProductOptions()['attributes_info'])): ?>
                                                        <?php $_options = $_item->getProductOptions()['attributes_info']; ?>
                                                        <dl class="item-options">
                                                            <?php foreach ($_options as $_option) : ?>
                                                                <?php $_formatedOptionValue = Mage::helper('catalog/product_configuration')->getFormattedOptionValue($_option); ?>
                                                                <dt><?php echo Mage::helper('core')->escapeHtml($_option['label'], null) ?></dt>
                                                                <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>>
                                                                    <?php echo $_formatedOptionValue['value'] ?>
                                                                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                                                        <div class="truncated_full_value">
                                                                            <dl class="item-options">
                                                                                <dt><?php echo Mage::helper('core')->escapeHtml($_option['label'], null) ?></dt>
                                                                                <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                                                                            </dl>
                                                                        </div>
                                                                    <?php endif; ?>
                                                                </dd>
                                                            <?php endforeach; ?>
                                                        </dl>
                                                    <?php elseif (isset($_item->getProductOptions()['options'])): ?>
                                                        <?php $_options = $_item->getProductOptions()['options']; ?>
                                                        <dl class="item-options">
                                                            <?php foreach ($_options as $_option) : ?>
                                                                <?php $_formatedOptionValue = Mage::helper('catalog/product_configuration')->getFormattedOptionValue($_option); ?>
                                                                <dt><?php echo Mage::helper('core')->escapeHtml($_option['label'], null) ?></dt>
                                                                <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>>
                                                                    <?php echo $_formatedOptionValue['value'] ?>
                                                                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                                                        <div class="truncated_full_value">
                                                                            <dl class="item-options">
                                                                                <dt><?php echo Mage::helper('core')->escapeHtml($_option['label'], null) ?></dt>
                                                                                <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                                                                            </dl>
                                                                        </div>
                                                                    <?php endif; ?>
                                                                </dd>
                                                            <?php endforeach; ?>
                                                        </dl>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-2 col-xs-2 text-center track-order-text">
                                            <?php echo ($freeItem && isset($freeItem['quantity'])) ? round($_item->getQtyOrdered()) - $freeItem['quantity'] : round($_item->getQtyOrdered()); ?>
                                        </div>
                                        <div class="col-md-2 col-xs-3 track-order-text text-right no-padding-xs">
                                            <?php if ($freeItem && isset($freeItem['quantity']) && isset($freeItem['price'])): ?>
                                                <?php $total = $total - $freeItem['quantity'] * $freeItem['price'] ?>
                                                <?php $total_free_item_price += $freeItem['quantity'] * $freeItem['price']; ?>
                                            <?php endif; ?>
                                            <?php echo Mage::helper('checkout')->formatPrice($total); ?>
                                        </div>

                                    <?php endforeach; ?>
                                </div>

                                <div class="bot-row track-order-bot-row">
                                    <?php
                                    $sub_total = $first_order->getSubtotal();
                                    $grand_total = $first_order->getGrandTotal();
                                    $discount_value = $sub_total - $grand_total;
                                    $grand_discount = $discount_value - $total_free_item_price;
                                    ?>
                                    <div class="col-md-5 col-xs-5">
                                        <div class="payment-cart-text lh-30 fs14">Tạm tính:</div>
                                        <?php if ($grand_discount > 0): ?>
                                            <div class="payment-cart-text lh-30 fs14">Giảm giá:</div>
                                        <?php endif; ?>
                                        <div class="payment-cart-text lh-30 fs14">Thành tiền:</div>
                                        <div>(Miễn phí giao hàng toàn quốc)</div>
                                    </div>
                                    <div class="col-md-7 col-xs-7 text-right">
                                        <div class="o-cart-grandtotal lh-30"><?php echo Mage::helper('core')->currency($sub_total - $total_free_item_price, true, false); ?></div>
                                        <?php if ($grand_discount > 0): ?>
                                            <div class="o-cart-totaldiscount lh-30">
                                                - <?php echo Mage::helper('core')->currency($grand_discount, true, false); ?>
                                            </div>
                                        <?php endif; ?>
                                        <div class="o-cart-cod lh-30"><?php echo Mage::helper('core')->currency($grand_total, true, false); ?></div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="track-order-continue-shipping">
                                <button type="button" class="btn-continue-shopping btn-continue-float-right"
                                        title="<?php echo $this->__('Continue Shopping') ?>"
                                        onclick="window.location='<?php echo $this->getUrl() ?>'">
                                    <span><span><?php echo $this->__('Continue Shopping') ?></span></span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            <?php else: ?>
                <div class="row">
                    <div class="col-md-12 col-sm-12 list-no-products">
                        <img class="list-no-products-img"
                             src="<?php echo $this->getSkinUrl('images/giohangtrong.png'); ?>"/>
                        <span class="list-no-products-text">Không tìm thấy đơn hàng phù hợp!</span>
                        <button type="button" class="continue-shopping-btn"
                                onclick="continueShopping();">
                            Tiếp tục mua hàng
                            <img class="continue-shopping-ajax-loader hidden"
                                 src="<?php echo $this->getSkinUrl('images/ajax-loader-white.gif'); ?>"/>
                        </button>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>
<script type="text/javascript">

    var $j = jQuery.noConflict();

    preventKeyInput();

    if ($j(window).width() < 500) {
        toggleOrderList()
    }

    $j(window).on('resize', function () {
        if ($j(".search-list-orders").is(':hidden') && $j(window).width() >= 500) {
            $j(".search-list-orders").toggle()
        }
    });

    function preventKeyInput() {
        $j('input[type="number"]').keypress(function (e) {
            if (e.which == 8) { // to allow BackSpace
                return
            }
            if (e.which < 48 || e.which > 57 || e.keyCode == 13) {
                e.preventDefault();
            }
        });

        $j('.discount-input').keypress(function (e) {
            if (e.keyCode === 10 || e.keyCode === 13)
                e.preventDefault();
        });
    }

    function checkOrderDetail(value) {

        var orderId = $j(value).data("id");

        var track_order_item = "track-order-item-" + orderId;

        var data = {
            order_id: orderId
        };

        $j('.track-order-item').removeClass('track-order-item-active');
        $j('#' + track_order_item).addClass('track-order-item-active');

        $j('.track-order-detail').empty();
        $j('.track-order-detail-loading').removeClass('hidden');

        $j.ajax({
            url: "<?php echo $this->getUrl('tracking/order/detail') ?>",
            type: 'POST',
            dataType: 'json',
            data: data,
            success: function (response) {
                $j('.track-order-detail-loading').addClass('hidden');
                $j('.track-order-detail').append(response.order_detail_html);
            }
        });
    }

    var timeout = null;

    function doSearchOrder() {
        $j('.list-orders').empty();
        $j('.track-order-detail').empty();
        $j('.search-order-loading').removeClass('hidden');
        if (timeout) {
            clearTimeout(timeout);
        }
        timeout = setTimeout(function () {
            searchOrder();
        }, 1000);
    }

    // Xu ly ajax tim kiem don hang
    function searchOrder() {
        var form = $j('#search-order-form');
        var data = form.serializeArray();
        $j.ajax({
            url: form.attr('action'),
            type: form.attr('method'),
            dataType: 'json',
            data: data,
            success: function (response) {
                $j('.list-orders').empty();
                $j('.track-order-detail').empty();
                $j('.search-order-loading').addClass('hidden');
                $j('.list-orders').append(response.search_order_html);
                $j('.track-order-detail').append(response.order_detail_html);
            }
        });
    }

    function toggleOrderList() {
        $j(".search-list-orders").toggle(300, function () {
            if ($j(".search-list-orders").is(':hidden')) {
                $j('.tracking-order-mobile').find("i").toggleClass('fa-angle-up fa-angle-down');
            } else {
                $j('.tracking-order-mobile').find("i").toggleClass('fa-angle-down fa-angle-up');
            }
        });
    }

    /** Continue shopping **/
    function continueShopping() {
        $j('.continue-shopping-btn').prop('disabled', true);
        $j('.continue-shopping-ajax-loader').removeClass('hidden');
        window.location.href = '<?php echo $this->getUrl(); ?>';
    }
    /** End continue shopping **/
</script>
