<?php /**@var Ved_Checkout_Block_Shipping_Panel $this */ ?>

<?php
$_cartItems = [];
$quote = $this->getQuote();
$quoteItems = $quote->getAllVisibleItems();
foreach ($quoteItems as $_item) {
    $_productCartObj = new stdClass();
    $_productCartObj->name = $this->escapeHtml($_item->getName());
    $_productCartObj->id = intval($_item->getProduct()->getId());
    $_productCartObj->price = intval($_item->getPrice());
    $_productCartObj->quantity = intval($_item->getQty());
    $_cartItems[] = $_productCartObj;
}
?>
<script src="<?php echo $this->getSkinUrl('lib/checkout_shipping_page.js') ?>" type="application/javascript"></script>
<div class="panel address-list payment-address-block">
    <div class="panel-body pb-0">
        <div class="panel-title text-center">Thông tin giao hàng</div>

        <div class="panel-body pb-0">
            <form class="form-horizontal" role="form" id="address-info">
                <div class="form-group row">
                    <label for="full_name" class="col-lg-4 control-label label-input">
                        Họ tên <span class="red">*</span>
                    </label>
                    <div class="col-lg-8">
                        <input type="text" name="full_name" class="form-control address" id="full_name"
                               placeholder="Nhập họ tên" required>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="telephone" class="col-lg-4 control-label label-input">
                        Điện thoại di động <span class="red">*</span>
                    </label>
                    <div class="col-lg-8">
                        <input type="number" name="telephone" class="form-control address" id="telephone"
                               placeholder="Nhập số điện thoại"
                               required>
                    </div>
                </div>

                <input type="hidden" id="country_id" name="country_id" value="VN"/>
                <!--                <div class="form-group row" hidden="hidden">-->
                <!--                    <label for="country_id" class="col-lg-4 control-label label-input">-->
                <!--                        Quốc gia <span class="red">*</span>-->
                <!--                    </label>-->
                <!--                    <div class="col-lg-8">-->
                <!--                        <select name="country_id" class="form-control address" id="country_id" disabled="disabled">-->
                <!--                        </select>-->
                <!--                    </div>-->
                <!--                </div>-->
                <div class="form-group row">
                    <label for="region_id" class="col-lg-4 control-label label-input">
                        Tỉnh / Thành phố <span class="red">*</span>
                    </label>
                    <div class="col-lg-8">
                        <select name="region_id" class="form-control address" id="region_id" required>
                            <option value="">Chọn Tỉnh / Thành phố</option>
                            <?php
                            $cities = $this->getListCities();
                            foreach ($cities as $val => $name) {
                                echo '<option value="' . $val . '" >' . $name . '</option>';
                            }
                            ?>
                        </select>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="city_id" class="col-lg-4 control-label label-input">
                        Quận / Huyện <span class="red">*</span>
                    </label>
                    <div class="col-lg-8">
                        <select name="city_id" class="form-control address" id="city_id" required>
                            <option value="">Chọn Quận / Huyện</option>
                        </select>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="street" class="col-lg-4 control-label label-input">
                        Địa chỉ <span class="red">*</span>
                    </label>
                    <div class="col-lg-8">
                        <textarea name="street" class="form-control address" id="street" placeholder="Nhập địa chỉ"
                                  required></textarea>
                    </div>
                </div>

                <div class="form-group row mb-10">
                    <label for="telephone" class="col-lg-4 control-label label-input">
                        Địa chỉ Email
                    </label>
                    <div class="col-lg-8">
                        <input type="email" name="email" class="form-control address" id="email"
                               placeholder="Nhập email" required>
                        <span class="help-block"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="street" class="col-lg-4 control-label label-input">
                        Ghi chú
                    </label>
                    <div class="col-lg-8">
                        <textarea name="customer_note" class="mt-0 form-control note" id="customer_note" rows="5"
                                  placeholder="Thông tin ghi chú về: thời gian, địa điểm giao hàng, người nhận"
                                  required></textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="is_vat" class="col-lg-4 control-label label-input vat-label">
                        Yêu cầu viết hóa đơn
                    </label>
                    <div class="col-lg-8 vat-checkbox">
                        <input type="checkbox" class="vat-checkbox" name="is_vat" value="1">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="full_name" class="col-lg-4 control-label label-input">
                        Tên công ty <span class="red">*</span>
                    </label>
                    <div class="col-lg-8">
                        <input type="text" name="vat_name" class="form-control"
                               placeholder="Tên công ty" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="street" class="col-lg-4 control-label label-input">
                        Địa chỉ trên hóa đơn <span class="red">*</span>
                    </label>
                    <div class="col-lg-8">
                        <textarea name="vat_address" class="mt-0 form-control note" id="vat_address" rows="5"
                                  placeholder="Thông tin trên hóa đơn"
                                  required></textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="full_name" class="col-lg-4 control-label label-input">
                        Mã số thuế <span class="red">*</span>
                    </label>
                    <div class="col-lg-8">
                        <input type="text" name="vat_id" class="form-control"
                               placeholder="Mã số thuế" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="street" class="col-lg-4 control-label label-input">
                        Địa chỉ nhận hóa đơn <span class="red">*</span>
                    </label>
                    <div class="col-lg-8">
                        <textarea name="vat_address_to" class="mt-0 form-control note" id="customer_note2" rows="5"
                                  placeholder="Địa chỉ nhận hóa đơn"
                                  required></textarea>
                    </div>
                </div>
                <div class="form-group row end mb-0">
                    <div class="col-lg-8 col-lg-offset-4">
                        <button id="btn-address" type="button"
                                class="confirm-shipping-btn" value="create">
                            Giao đến địa chỉ này
                            <img class="confirm-shipping-ajax-loader hidden"
                                 src="<?php echo $this->getSkinUrl('images/ajax-loader-white.gif'); ?>"/>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    var $j = jQuery.noConflict();
    $j('input[type="number"]').keypress(function (e) {
        var a = [];
        var k = e.which;

        for (var i = 48; i < 58; i++)
            a.push(i);

        if (!(a.indexOf(k) >= 0))
            e.preventDefault();
    });

    $j('#region_id').change(function () {
        var region_id = this.value;
        $j("#city_id").empty();
        $j("#city_id").load("<?php echo $this->getUrl('checkout/shipping/getDistrictsInCity')  ?>?cityId=" + region_id + "&defaultDistrict=");
    });

    $j("#default_shipping_address").change(function () {
        if (this.checked) {
            $j(this).parent().addClass("checked");
        } else {
            $j(this).parent().removeClass("checked");
        }
    });

    $j(document).ready(function () {
        <?php $session = Mage::getSingleton('customer/session'); ?>
        <?php if ($session->isLoggedIn()): ?>
        <?php
        $customer = $session->getCustomer();
        $defaultShipping = $customer->getDefaultShippingAddress();
        ?>
        $j("#full_name").val('<?php echo $customer->getFirstname()?>');
        $j("#telephone").val('<?php echo $customer->getPhoneNumber()?>');
        var region_id, street = '', city;
        region_id = '<?php echo $defaultShipping->getRegionId()?>';
        city = '<?php echo $defaultShipping->getCity()?>';
        <?php foreach($defaultShipping->getStreet() as $value):?>
            street += '<?php echo trim(preg_replace('/\s\s+/', ' ', $value))?>' + ' ';
        <?php endforeach;?>
        $j("#region_id").val(region_id);
        $j("#city_id").load("<?php echo $this->getUrl('checkout/shipping/getDistrictsInCity') ?>?cityId="
            + region_id + "&defaultDistrict=" + encodeURI(city));
        $j("#street").val(street);
        <?php else:?>

        var data = JSON.parse(localStorage.getItem('tekshop_address'));

        if (data) {
            $j("#full_name").val(data.full_name);
            $j("#email").val(data.email);
            $j("#telephone").val(data.telephone);
            $j("#region_id").val(data.region_id);
            $j("input[name*=vat][type=text],textarea[name*=vat]").each(function (e) {
                $j(this).val(data[$j(this).attr("name")]);
            });
            if (data.is_vat)
                $j('[name=is_vat]').attr('checked', 'checked');
            $j.ajax({
                url: "<?php echo $this->getUrl('checkout/shipping/getDistrictNameById') ?>",
                type: "POST",
                data: {
                    cityId: data.city_id
                },
                dataType: "json"
            }).done(function (response) {
                $j("#city_id").load("<?php echo $this->getUrl('checkout/shipping/getDistrictsInCity') ?>?cityId=" + data.region_id + "&defaultDistrict=" + encodeURI(response.district_name));
            });

            $j("#street").val(data.street);
            $j("#customer_note").val(data.customer_note);
            $j("#customer_note2").val(data.customer_note);
        }
        <?php endif;?>
    });

    $j.fn.serializeObject = function () {
        var o = {};
        var a = this.serializeArray();
        $j.each(a, function () {
            if (o[this.name] !== undefined) {
                if (!o[this.name].push) {
                    o[this.name] = [o[this.name]];
                }
                o[this.name].push(this.value || '');
            } else {
                o[this.name] = this.value || '';
            }
        });
        return o;
    };

    $j("#btn-address").click(function (event) {
        var url = "<?php echo $this->getUrl('checkout/shipping/saveShipping');  ?>";

        localStorage.setItem('tekshop_address', JSON.stringify($j("#address-info").serializeObject()));
        if ($j('input[name=is_vat]').is(":checked")) {
            if (!$j('input[name=vat_name]').val())
                return alert("Vui lòng nhập Tên công ty");
            if (!$j('textarea[name=vat_address]').val())
                return alert("Vui lòng nhập Thông tin trên hóa đơn");
            if (!$j('input[name=vat_id]').val())
                return alert("Vui lòng nhập Mã số thuế");
            if (!$j('textarea[name=vat_address_to]').val())
                return alert("Vui lòng nhập Địa chỉ nhận hóa đơn")
        }
        var full_name = $j("#full_name").val().trim();
        var email = $j("#email").val().trim();
        var telephone = $j("#telephone").val().trim();
        var region_id = $j("#region_id").val().trim();
        var city_id = $j("#city_id").val().trim();
        var street = $j("#street").val().trim();
        var customer_note = $j("#customer_note2").val().trim();
        $j("#address-info input[type=text],textarea,input[type=number]").each(function (e) {
            $j(this).val($j(this).val().trim());
        });
        if (full_name === '' || typeof(full_name) === 'undefined') {
            alert('Bạn chưa nhập họ tên');
        }
        else if (telephone === '' || typeof(telephone) === 'undefined') {
            alert('Bạn chưa nhập số điện thoại');
        }
        else if (telephone !== '' && !validateVNPhoneNumber(telephone)) {
            alert('Số điện thoại không đúng định dạng (phải có dạng 84xxx hoặc 0xxx, chứa 10 hoặc 11 ký tự)');
        }
        else if (region_id === '' || typeof(region_id) === 'undefined') {
            alert('Bạn chưa nhập Tỉnh/Thành phố');
        }
        else if (city_id === '' || typeof(city_id) === 'undefined') {
            alert('Bạn chưa nhập Quận/Huyện');
        }
        else if (street === '' || typeof(street) === 'undefined') {
            alert('Bạn chưa nhập địa chỉ');
        }
        else if (email !== '' && !validateEmail(email)) {
            alert('Địa chỉ Email không hợp lệ');
        }
        else {
            /** Track checkout step 2 **/
            var cartItems = <?php echo json_encode($_cartItems); ?>;
            dataLayer.push({
                'event': 'checkout',
                'ecommerce': {
                    'checkout': {
                        'actionField': {'step': 2},
                        'products': cartItems
                    }
                }
            });

            $j('.confirm-shipping-btn').prop('disabled', true);
            $j('.confirm-shipping-ajax-loader').removeClass('hidden');
            $j.ajax({
                url: url,
                type: "POST",
                data: $j("#address-info").serialize(),
                dataType: "json"
            }).done(function (data) {
                if (data.redirect != null) {
                    window.location.href = data.redirect;
                }
                else {
                    $j('.confirm-shipping-btn').prop('disabled', false);
                    $j('.confirm-shipping-ajax-loader').addClass('hidden');
                    if (data.message != null) {
                        alert(data.message);
                    }
                }
            });
        }
    });

    $j("#btn-cancel").click(function (event) {
        $j("#newblock").html("");
    });

    function validateEmail(email) {
        var re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
        return re.test(email);
    }

    function validateVNPhoneNumber(phone_number) {
        var phoneRe = /^\+?(84|0)([1-9]\d{8,9})$/;
        return phoneRe.test(phone_number);
    }
</script>
