<?php /** @var Teko_Amp_Block_Adminhtml_Amp_Config $this */ ?>
<?php
$config = $this->getConfig();
?>
<div>
    <form action="<?php echo $this->getUpdateUrl() ?>">
        <table>
            <tr>
                <th>Routing Key</th>
                <th>Trạng thái</th>
            </tr>
            <?php foreach ($config as $key => $value): ?>
                <tr>
                    <td>
                        <?php echo $value->getData('routing_key') ?>
                    </td>
                    <td>
                        <select name="config[<?php echo $value->getData('id') ?>]">
                            <option
                                <?php echo $value->getData('status') == '0' ? 'selected' : null ?>
                                    value="0">Vô hiệu
                            </option>
                            <option
                                <?php echo $value->getData('status') == '1' ? 'selected' : null ?>
                                    value="1">Hiệu lực
                            </option>
                        </select>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
        <button type="submit">Cập nhật</button>
    </form>
</div>