<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>"
      lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/bootbox.min.js'); ?>"></script>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/style.min.css'); ?>">
</head>
<body class="tiki-shipping-address">
<?php echo $this->getChildHtml('after_body_start') ?>

<?php echo $this->getChildHtml('global_notices') ?>

<?php Mage::getSingleton('core/session')->setWelcomeMessage('true'); ?>
<div id="preloader" class="preloaderlight">
    <h1>
        <img src="<?php echo $this->getSkinUrl('images/tekedu.gif') ?>" alt="Logo"/>
    </h1>
</div>
<script type="text/javascript">
    setTimeout(function () {
        jQuery("#preloader").fadeOut();
    }, 50);
</script>

<div class="wrap">
    <?php echo $this->getChildHtml('header') ?>
    <div class="container">
        <div class="row visible-lg-block">

            <?php echo $this->getChildHtml('top_slider') ?>
            <?php echo $this->getChildHtml('breadcrumbs') ?>
        </div>
        <div class="row row-style-2" style="min-height: 680px;">
            <div class="col-lg-7 col-md-12 cart-col-1">
                <?php echo $this->getChildHtml('global_messages') ?>
                <div class="shipping-header payment-shipping-header">
                    <div class="row bs-wizard">
                        <div class="col-lg-4 col-md-4 col-xs-4 col-sm-4 bs-wizard-step complete">
                            <div class="text-center bs-wizard-stepnum text-step">
                                <span class="color-bar-text">Địa chỉ giao hàng</span>
                            </div>
                            <div class="progress">
                                <div class="progress-bar color-bar"></div>
                            </div>
                            <span class="bs-wizard-dot color-bar">1</span>
                        </div>

                        <div class="col-lg-4 col-md-4 col-xs-4 col-sm-4 bs-wizard-step active">
                            <div class="text-center bs-wizard-stepnum text-step">
                                <span class="hidden-xs color-bar-text text-nowrap">Thanh Toán &amp; Đặt Mua</span>
                                <span class="visible-xs-inline-block color-bar-text text-nowrap">Thanh Toán &amp; Đặt Mua</span>
                            </div>
                            <div class="progress">
                                <div class="progress-bar color-bar"></div>
                            </div>
                            <span class="bs-wizard-dot color-bar">2</span>
                        </div>

                        <div class="col-lg-4 col-md-4 col-xs-4 col-sm-4 bs-wizard-step disabled">
                            <div class="text-center bs-wizard-stepnum text-step">
                                <span class="hidden-xs">Hoàn tất</span>
                                <span class="visible-xs-inline-block">Hoàn tất</span>
                            </div>
                            <div class="progress">
                                <div class="progress-bar"></div>
                            </div>
                            <span class="bs-wizard-dot color-deactive-bar">3</span>
                        </div>
                    </div>
                </div>

                <?php
                $quote = Mage::getSingleton('checkout/session')->getQuote();
                $address = $quote->getShippingAddress();
                ?>

                <div class="mt-15"></div>
                <div class="panel panel-default cart br-0 panel-address">
                    <div class="panel-body no-padding panel-address-block">
                        <h3 class="panel-cart-title mt-0 mb-20">Địa chỉ giao hàng</h3>
                        <div class="information">
                            <div class="address-text"><?php echo $address->getName(); ?></div>
                            <div class="address-text"><?php echo $address->getStreetFull().', '.ucfirst(mb_strtolower($address->getCity(), 'UTF-8')).', '.$address->getRegion(); ?></div>
                            <div class="address-text"><b>Điện thoại:</b> <?php echo $address->getTelephone() ?></div>
                            <?php if ($address->getEmail()!=''): ?><div class="address-text"><b>Email:</b> <?php echo $address->getEmail(); ?></div><?php endif; ?>
                            <?php if ($quote->getAffiliateCode()): ?>
                                <div class="address-text">
                                    <b>Mã giới thiệu:</b>
                                    <?php echo $quote->getAffiliateCode() ?>
                                </div>
                            <?php endif; ?>
                            <?php if ($address->getCustomerNotes()!=''): ?><div class="address-text"><b>Ghi chú:</b> <?php echo $address->getCustomerNotes(); ?></div><?php endif; ?>
                        </div>
                    </div>
                </div>

                <?php echo $this->getChildHtml('content') ?>

            </div>
            <div class="col-lg-5 col-md-12 cart-col-2 right-thanhtoan">
                <?php echo $this->getChildHtml('right') ?>
            </div>
        </div>
    </div>
</div>
<?php //echo $this->getChildHtml('footer') ?>
<?php //echo $this->getChildHtml('global_cookie_notice') ?>
<?php //echo $this->getChildHtml('before_body_end') ?>
<div>
    <?php echo $this->getChildHtml('footer') ?>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
