<?php
/**
 * Created by PhpStorm.
 * User: Teko
 * Date: 9/6/2017
 * Time: 11:10 AM
 */
?>

<?php
$currentUser = Mage::getSingleton('customer/session')->getCustomer();
$agentInfo = json_decode($currentUser->getAgentInfo());
$agentChannels = array(
    1 => 'Mạng xã hội',
    2 => 'Diễn đàn/Website'
);
?>

<style>
    /*basic reset*/
    * {
        margin: 0;
        padding: 0;
    }

    /*adding a black bg to the body to make things clearer*/
    body {
        background: black;
    }
</style>

<script>
    dataLayer = [];
</script>

<?php
$session = Mage::getSingleton('customer/session');
?>

<?php if ($session->isLoggedIn()): ?>
    <?php if ($currentUser->getIsAgentDeleted() == 1): ?>
        <?php echo $this->getChildHtml('agent.warning') ?>
    <?php else: ?>
        <div class="agent-content">
            <div class="row row-eq-height">

                <?php echo $this->getChildHtml('agent.navigation') ?>

                <div class="col-md-10 col-sm-10 col-xs-12">
                    <div class="row mr-0">
                        <div class="col-md-12 col-sm-12 col-xs-12 pl-30-xs">
                            <div class="agent-box agent-post-history mb-15">
                                <div class="agent-box-title h-40">
                                    Danh sách đặc vụ giới thiệu
                                    <div class="agent-btn clear-filter-btn pull-right">
                                        Bỏ lọc
                                    </div>
                                </div>

                                <div class="agent-recommendation-total">Số đặc vụ đang lọc/Tổng số đặc vụ: <span class="agent-filtered-count"></span>/<span class="agent-total-count"></span></div>

                                <div class="table-responsive">
                                    <table id="datatable" class="table table-striped agent-table">
                                        <thead>
                                        <tr>
                                            <th>STT</th>
                                            <th>Mã đặc vụ</th>
                                            <th>Tên đặc vụ</th>
                                            <th>Ngày giới thiệu</th>
                                            <th>Điểm thành tích được hưởng</th>
                                        </tr>
                                        </thead>
                                        <tfoot>
                                        <tr>
                                            <th></th>
                                            <th></th>
                                            <th></th>
                                            <th></th>
                                            <th></th>
                                        </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php endif; ?>
<?php else: ?>
    <?php echo $this->getChildHtml('agent.warning_login') ?>
<?php endif; ?>

<script>
    var $j = jQuery.noConflict();
    var win = $j(window);

    $j('.main-container').find('.container').addClass('ml-0');

    $j('input[type="number"]').keypress(function (e) {
        var a = [];
        var k = e.which;

        for (i = 48; i < 58; i++)
            a.push(i);

        if (!(a.indexOf(k) >= 0))
            e.preventDefault();
    });

    $j(document).ready(function () {
        $j('.main-container').find('.container').addClass('w-100');
        $j('.build-pc-btn').addClass('no-display');
        $j('.facebook-message').addClass('no-display');

        $j("#datepicker").datepicker({
            dateFormat: 'dd/mm/yy',
            changeMonth: true,
            changeYear: true,
            yearRange: "1950:2017"
        });

        $j('#datatable tfoot th').each(function () {
            var title = $j('#datatable thead th').eq($j(this).index()).text();
            var index = $j(this).index();
            if (index === 1 || index === 2) {
                $j(this).html('<input type="text" placeholder="' + title + '" />');
            }
            else if (index === 3) {
                $j(this).html('<input id="min" class="mb-5" type="text" placeholder="Từ ngày"><input id="max" type="text" placeholder="Đến ngày">');
            }
        });

        // Render datatable
        var table = $j('#datatable').DataTable({
            "ajax": '<?php echo $this->getUrl('agent/index/getAgentList')?>?user_id=<?php echo $currentUser->getId() ?>',
            "pagingType": "full_numbers",
            "language": {
                "lengthMenu": "Hiển thị _MENU_ bản ghi mỗi trang",
                "zeroRecords": "Không tìm thấy dữ liệu phù hợp",
                "info": "Trang _PAGE_ / _PAGES_",
                "infoEmpty": "",
                "infoFiltered": "",
                "search": "Tìm kiếm:",
                "paginate": {
                    "previous": "Trước",
                    "next": "Sau",
                    "first": "Đầu",
                    "last": "Cuối"
                }
            },
            "columns": [
                {"width": "10%"},
                {"width": "20%"},
                {"width": "30%"},
                {"width": "20%"},
                {"width": "20%"}
            ],
            "initComplete": function (settings, json) {
                $j('div.datatable-loading').remove();

                this.api().columns().every(function () {
                    var that = this;
                    var index = that.index();
                    if (index === 1 || index === 2) {
                        $j('input', this.footer()).on('keyup change', function () {
                            if (that.search() !== this.value) {
                                that
                                    .search(this.value)
                                    .draw();
                            }
                        });
                    }

                });
            },
            "footerCallback": function (row, data, start, end, display) {
                var api = this.api(), data;

                // Remove the formatting to get integer data for summation
                var intVal = function (i) {
                    return typeof i === 'string' ?
                        i.replace(/[\$,]/g, '') * 1 :
                        typeof i === 'number' ?
                            i : 0;
                };

                // Total over all pages
                total = api
                    .column(4, {'search': 'applied'})
                    .data()
                    .reduce(function (a, b) {
                        return intVal(a) + intVal(b);
                    }, 0);

                // Update footer
                $j(api.column(4).footer()).html(
                    'Tổng điểm: ' + total
                );

                getTotalRows();
                getFilteredRows();
            }
        });

        function getTotalRows() {
            $j('.agent-total-count').empty().append($j('#datatable').DataTable().rows().count());
        }

        function getFilteredRows(){
            var info = $j('#datatable').DataTable().page.info();
            $j('.agent-filtered-count').empty().append(info.recordsDisplay);
        }

        // Filter date range
        $j.fn.dataTable.ext.search.push(
            function (settings, data, dataIndex) {
                var min = $j('#min').datepicker("getDate");
                var max = $j('#max').datepicker("getDate");
                if (max) {
                    max.setHours(23, 59, 59, 999);
                }

                var startDate = new Date(data[3].split("|")[0]);

                if (min == null && max == null) {
                    return true;
                }
                if (min == null && startDate <= max) {
                    return true;
                }
                if (max == null && startDate >= min) {
                    return true;
                }
                if (startDate <= max && startDate >= min) {
                    return true;
                }
                return false;
            }
        );

        $j("#min").datepicker({
            onSelect: function () {
                table.draw();
            },
            dateFormat: 'dd/mm/yy',
            changeMonth: true,
            changeYear: true,
            yearRange: "1950:2017"
        });

        $j("#max").datepicker({
            onSelect: function () {
                table.draw();
            },
            dateFormat: 'dd/mm/yy',
            changeMonth: true,
            changeYear: true,
            yearRange: "1950:2017"
        });

        $j('#min, #max').change(function () {
            table.draw();
        });
        // End filter date range

        // Add loading text when call ajax
        $j('tbody').empty();
        $j('<div class="datatable-loading" style="padding: 15px 0; text-align: center;">Đang tải dữ liệu...</div>').appendTo('tbody');
        $j('.datatable-loading').css('width', $j('#datatable').width() + 'px');
    });

    // Clear all filters
    $j('.clear-filter-btn').click(function () {
        $j('#datatable tfoot input').val('').change();
        $j('#datatable tfoot select').val('').change();
        $j('#min').datepicker('setDate', '');
        $j('#max').datepicker('setDate', '');
    });
</script>
