<div class="content">
    <div class="row maintenance-content">
        <div class="col-md-6 col-sm-6 col-xs-12 text-center maintenance-content-block">
            <div class="maintenance-title">Oops!!</div>
            <p>PHONG VŨ hiện đang có lỗi xảy ra, bạn vui lòng truy cập lại sau.</p>
            <p>Mã lỗi: <?php echo $this->reportId ?></p>
            <p>Xem thông báo mới về hệ thống PHONG VŨ tại <a href="https://www.facebook.com/phongvuvietnam">đây</a></p>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <img class="maintenance-img" src="https://phongvu.vn/baotri.svg">
        </div>
    </div>
</div>
