<?php
/**
 * @category    Mana
 * @package     Mana_Filters
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * Template for showing options for filter as a HTML list
 * @author Mana Team
 * Injected instead of standard catalog/layer/filter.phtml in Mana_Filters_Block_Filter_Attribute constructor.
 * This template is overridden by copying (template body was pasted from catalog/layer/filter.phtml
 * and modified as needed). All changes are marked with comments.
 */
/* @var $this Mana_Filters_Block_Filter_Attribute */
?>
<?php foreach ($this->getItems() as $_item): ?>
    <?php if ($_item->getCount() > 0): ?>
        <a class="filter-section-item <?php if ($_item->getMSelected()): ?>active <?php endif; ?><?php if ($_item->getFilter()->getAttributeModel()->getAttributeCode() == 'price'): ?>w-100<?php endif; ?>"
           data-filter-url="<?php echo ($_item->getMSelected()) ? $this->urlEscape($_item->getRemoveUrl()) : $this->urlEscape($_item->getUrl()); ?>"
           data-attribute-code="<?php echo $_item->getFilter()->getAttributeModel()->getAttributeCode(); ?>"
           data-attribute-value="<?php echo $_item->getValue(); ?>">
            <input type="checkbox" class="filter-section-checkbox"
                   data-filter-url="<?php echo ($_item->getMSelected()) ? $this->urlEscape($_item->getRemoveUrl()) : $this->urlEscape($_item->getUrl()); ?>"
                   data-attribute-code="<?php echo $_item->getFilter()->getAttributeModel()->getAttributeCode(); ?>"
                   data-attribute-value="<?php echo $_item->getValue(); ?>"
                   <?php if ($_item->getMSelected()): ?>checked="checked"<?php endif; ?>>
            <?php echo $_item->getLabel() ?>
            <?php if ($this->shouldDisplayProductCount()): ?>
                <span>(<?php echo $_item->getCount() ?>)</span>
            <?php endif; ?>
        </a>
    <?php endif; ?>
<?php endforeach; ?>