<?php $_productImpressions = []; ?>
<?php
$promoCat = Mage::getModel('catalog/category')
    ->getCollection()
    ->addAttributeToFilter('url_key', 'promo-cats')
    ->getFirstItem();
?>
<?php
$tagProduct = Mage::getModel('tag/tag_relation')
    ->setTagId(1)// Bao ke gia
    ->setStoreId((Mage::app()->getStore()->getId()))
    ->getProductIds();
$tagOnlinePaymentIds = Mage::getModel('tag/tag_relation')
    ->setTagId(3)// Giam gia thanh toan online
    ->setStoreId(Mage::app()->getStore()->getId())
    ->getProductIds();
?>
<?php $_promoSubcatIds = $promoCat->getResource()->getChildren($promoCat); ?>
<?php if (count($_promoSubcatIds) > 0): ?>
    <?php foreach ($_promoSubcatIds as $key => $_promoSubcatId): ?>
        <?php $_promoSubcat = Mage::getModel('catalog/category')->load($_promoSubcatId); ?>
        <div class="col-xs-12 promo-products-section <?php if ($key === count($_promoSubcatIds) - 1): ?>last<?php endif; ?>">
            <div class="cat-name"><?php echo $_promoSubcat->getName(); ?></div>
            <?php
            $_products = $_promoSubcat->getProductCollection()
                ->addAttributeToFilter('instock', array('in' => array(1, 6)))->setPageSize(5)->setCurPage(1);
            Mage::getModel('catalog/layer')->prepareProductCollection($_products);
            ?>
            <?php if (count($_products) > 0): ?>
                <div class="promo-products">
                    <?php foreach ($_products as $_product): ?>
                        <?php
                        $_productObj = new stdClass();
                        $_productObj->name = $this->escapeHtml($_product->getName());
                        $_productObj->id = intval($_product->getId());
                        $_productObj->price = intval($_product->getFinalPrice());
                        $_productObj->list = 'Home Page';
                        $_productImpressions[] = $_productObj;
                        ?>
                        <?php
                        $oldPrice = $_product->getPrice();
                        $finalPrice = $_product->getFinalPrice();
                        ?>
                        <?php
                        $includedProduct = json_decode($this->helper('catalog/output')->productAttribute($_product, nl2br($_product->getPromotionInfo()), 'promotion_info'));
                        $includedProductIds = [];
                        $includedProductQty = [];
                        if ($includedProduct) {
                            $includedProductIds = json_decode($this->helper('catalog/output')->productAttribute($_product, nl2br($_product->getPromotionInfo()), 'promotion_info'))->promotion_ids;
                            $includedProductQty = json_decode($this->helper('catalog/output')->productAttribute($_product, nl2br($_product->getPromotionInfo()), 'promotion_info'))->promotion_qty;
                        }
                        $promotionInfoHtml = '<b>Tặng kèm:</b>';
                        ?>
                        <?php if (count($includedProductIds) > 0 && count($includedProductQty) > 0): ?>
                            <?php foreach ($includedProductIds as $key => $id): ?>
                                <?php
                                $_includedProduct = Mage::getModel('catalog/product')->load($id);
                                $promotionInfoHtml .= '</br>- ' . $includedProductQty[$key] . ' ' . $this->escapeHtml($_includedProduct->getName()) . '';
                                ?>
                            <?php endforeach; ?>
                        <?php endif; ?>
                        <div class="row">
                            <div class="promo-products-item"
                                 onclick="trackProductClicks(this); window.location.href='<?php echo $_product->getProductFullUrl(); ?>'"
                                 data-id="<?php echo $_product->getId(); ?>"
                                 data-name="<?php echo $this->escapeHtml($_product->getName()); ?>"
                                 data-price="<?php echo $_product->getFinalPrice(); ?>"
                            >
                                <?php if ($oldPrice != $finalPrice) : ?>
                                    <div class="promo-ribbon">
                                        -<?php echo number_format(($oldPrice - $finalPrice) / $oldPrice * 100, 0) . "%" ?>
                                    </div>
                                <?php endif; ?>
                                <div class="col-xs-4">
                                    <?php if (in_array((string)$_product->getId(), $tagProduct)): ?>
                                        <img class="list-tag"
                                             src="<?php echo $this->getSkinUrl('images/tag.png') ?>"/>
                                    <?php endif; ?>
                                    <img class="product-img lazy" src="" alt=""
                                         data-src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(130, 130); ?>"/>

                                </div>
                                <div class="col-xs-8 promo-info">
                                    <div class="product-name">
                                        <?php echo $this->escapeHtml($_product->getName()); ?>
                                    </div>
                                    <div class="product-price-block">
                                        <div class="old-price">
                                            <?php if ($oldPrice != $finalPrice) : ?>
                                                <?php echo number_format($oldPrice, 0, ",", ".") . " ₫"; ?>
                                            <?php endif; ?>
                                        </div>
                                        <div class="final-price">
                                            <?php echo number_format($finalPrice, 0, ",", ".") . " ₫"; ?>
                                        </div>
                                        <?php if (count($includedProductIds) > 0 && count($includedProductQty) > 0): ?>
                                            <img class="product-gift-icon promo-product-gift-icon" data-toggle="tooltip"
                                                 title="<?php echo $promotionInfoHtml; ?>"
                                                 src="<?php echo $this->getSkinUrl('images/icon_Gift.svg'); ?>"/>
                                        <?php endif; ?>
                                    </div>
                                    <div class="tag-online-payment">
                                        <?php if (in_array($_product->getId(), $tagOnlinePaymentIds)): ?>
                                            <img src="<?php echo $this->getSkinUrl('images/icon_Notify.svg'); ?>"/>
                                            Áp dụng đặt hàng online
                                        <?php endif; ?>
                                    </div>

                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
    <script type="text/javascript">
        /** Track product impressions **/
        var productImpressions = <?php echo json_encode($_productImpressions); ?>;
        dataLayer.push({
            'event': 'productImpressions',
            'ecommerce': {
                'currencyCode': 'VND',
                'impressions': productImpressions
            }
        });
    </script>
<?php endif; ?>

