<?php $_productImpressions = []; ?>
<?php
$_recentlyProducts = Mage::getSingleton('Mage_Reports_Block_Product_Viewed')->getItemsCollection()
    ->addAttributeToFilter('instock', array('in' => array(1, 6)));
?>
<?php if (count($_recentlyProducts) > 0): ?>
    <?php
    $tagProduct = Mage::getModel('tag/tag_relation')
        ->setTagId(1)// Bao ke gia
        ->setStoreId((Mage::app()->getStore()->getId()))
        ->getProductIds();
    $tagOnlinePaymentIds = Mage::getModel('tag/tag_relation')
        ->setTagId(3)// Giam gia thanh toan online
        ->setStoreId(Mage::app()->getStore()->getId())
        ->getProductIds();
    ?>
    <div class="cat-name">Sản phẩm xem gần đây</div>
    <div class="row recently-viewed-products">
        <?php foreach ($_recentlyProducts as $_product): ?>
            <?php
            $_productObj = new stdClass();
            $_productObj->name = $this->escapeHtml($_product->getName());
            $_productObj->id = intval($_product->getId());
            $_productObj->price = intval($_product->getFinalPrice());
            $_productObj->list = 'Home Page';
            $_productImpressions[] = $_productObj;
            ?>
            <?php
            $oldPrice = $_product->getPrice();
            $finalPrice = $_product->getFinalPrice();
            ?>
            <?php
            $includedProduct = json_decode($this->helper('catalog/output')->productAttribute($_product, nl2br($_product->getPromotionInfo()), 'promotion_info'));
            $includedProductIds = [];
            $includedProductQty = [];
            if ($includedProduct) {
                $includedProductIds = json_decode($this->helper('catalog/output')->productAttribute($_product, nl2br($_product->getPromotionInfo()), 'promotion_info'))->promotion_ids;
                $includedProductQty = json_decode($this->helper('catalog/output')->productAttribute($_product, nl2br($_product->getPromotionInfo()), 'promotion_info'))->promotion_qty;
            }
            $promotionInfoHtml = '<b>Tặng kèm:</b>';
            ?>
            <?php if (count($includedProductIds) > 0 && count($includedProductQty) > 0): ?>
                <?php foreach ($includedProductIds as $key => $id): ?>
                    <?php
                    $_includedProduct = Mage::getModel('catalog/product')->load($id);
                    $promotionInfoHtml .= '</br>- ' . $includedProductQty[$key] . ' ' . $this->escapeHtml($_includedProduct->getName()) . '';
                    ?>
                <?php endforeach; ?>
            <?php endif; ?>
            <div class="col-xs-4 cat-products-item"
                 onclick="trackProductClicks(this); window.location.href='<?php echo $_product->getProductFullUrl(); ?>'"
                 data-id="<?php echo $_product->getId(); ?>"
                 data-name="<?php echo $this->escapeHtml($_product->getName()); ?>"
                 data-price="<?php echo $_product->getFinalPrice(); ?>"
            >
                <?php if (in_array((string)$_product->getId(), $tagProduct)): ?>
                    <img class="list-tag"
                         src='<?php echo $this->getSkinUrl('images/tag.png') ?>'/>
                <?php endif; ?>

                <img class="product-img lazy" src="" alt=""
                     data-src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(130, 130); ?>"/>
                <div class="product-name">
                    <?php echo $this->escapeHtml($_product->getName()); ?>
                </div>
                <div class="product-price-block">
                    <div class="old-price">
                        <?php if ($oldPrice != $finalPrice) : ?>
                            <?php echo number_format($oldPrice, 0, ",", ".") . " ₫"; ?>
                        <?php endif; ?>
                    </div>
                    <div class="final-price">
                        <?php echo number_format($finalPrice, 0, ",", ".") . " ₫"; ?>
                    </div>
                    <?php if (count($includedProductIds) > 0 && count($includedProductQty) > 0): ?>
                        <img class="product-gift-icon" data-toggle="tooltip"
                             title="<?php echo $promotionInfoHtml; ?>"
                             src="<?php echo $this->getSkinUrl('images/icon_Gift.svg'); ?>"/>
                    <?php endif; ?>
                </div>
                <div class="tag-online-payment">
                    <?php if (in_array($_product->getId(), $tagOnlinePaymentIds)): ?>
                        <img src="<?php echo $this->getSkinUrl('images/icon_Notify.svg'); ?>"/>
                        Áp dụng đặt hàng online
                    <?php endif; ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <script type="text/javascript">
        /** Track product impressions **/
        var productImpressions = <?php echo json_encode($_productImpressions); ?>;
        dataLayer.push({
            'event': 'productImpressions',
            'ecommerce': {
                'currencyCode': 'VND',
                'impressions': productImpressions
            }
        });
    </script>
<?php endif; ?>
