<!DOCTYPE html>
<html lang="en">
<head>
    <?php echo $this->getChildHtml('head'); ?>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('lib/checkout.css'); ?>"/>

    <script type="text/javascript">
        var dataLayer = [];
    </script>
</head>
<body>

<!-- Google Tag Manager (noscript) -->
<noscript>
    <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-W6CW7K7"
            height="0" width="0" style="display:none;visibility:hidden"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->

<div class="wrapper">
    <!-- Start Header-->
    <?php echo $this->getChildHtml('header'); ?>
    <!-- End Header-->
    <!-- Start Content-->
    <?php echo $this->getChildHtml('breadcrumbs'); ?>
    <div class="content">

        <!--Breadcrumb-->
        <div class="row tek-breadcrumb">
            <div class="col-md-10 col-md-offset-1 content-section">
                <div class="tek-breadcrumb-content"></div>
                <div class="tek-breadcrumb-main">
                    <span>Chọn phương thức thanh toán</span>
                </div>
            </div>
        </div>
        <!--End Breadcrumb-->

        <div class="row">
            <div class="col-md-10 col-md-offset-1 content-section payment-content-section mb-20">
                <div class="row">
                    <div class="col-md-7 col-sm-7">
                        <?php echo $this->getChildHtml('global_messages') ?>
                        <div class="shipping-header payment-shipping-header">
                            <div class="row bs-wizard">
                                <div class="col-md-4 col-sm-4 bs-wizard-step complete">
                                    <div class="text-center bs-wizard-stepnum text-step">
                                        <span class="color-bar-text">Địa chỉ giao hàng</span>
                                    </div>
                                    <div class="progress">
                                        <div class="progress-bar color-bar"></div>
                                    </div>
                                    <span class="bs-wizard-dot color-bar">1</span>
                                </div>

                                <div class="col-md-4 col-sm-4 bs-wizard-step active">
                                    <div class="text-center bs-wizard-stepnum text-step">
                                        <span class="hidden-xs color-bar-text text-nowrap">Thanh Toán &amp; Đặt Mua</span>
                                        <span class="visible-xs-inline-block color-bar-text text-nowrap">Thanh Toán &amp; Đặt Mua</span>
                                    </div>
                                    <div class="progress">
                                        <div class="progress-bar color-bar"></div>
                                    </div>
                                    <span class="bs-wizard-dot color-bar">2</span>
                                </div>

                                <div class="col-md-4 col-sm-4 bs-wizard-step disabled">
                                    <div class="text-center bs-wizard-stepnum text-step">
                                        <span class="hidden-xs">Hoàn tất</span>
                                        <span class="visible-xs-inline-block">Hoàn tất</span>
                                    </div>
                                    <div class="progress">
                                        <div class="progress-bar"></div>
                                    </div>
                                    <span class="bs-wizard-dot color-deactive-bar">3</span>
                                </div>
                            </div>
                        </div>

                        <?php
                        $quote = Mage::getSingleton('checkout/session')->getQuote();
                        $address = $quote->getShippingAddress();
                        ?>
                        <input type="hidden" id="instalname" value="<?php echo $address->getName(); ?>"/>
                        <input type="hidden" id="instalphone" value="<?php echo $address->getTelephone(); ?>"/>
                        <input type="hidden" id="instalcity" value="<?php echo $address->getRegion(); ?>"/>
                        <input type="hidden" id="instaladdress"
                               value="<?php echo $address->getStreetFull() . ', ' . ucfirst(mb_strtolower($address->getCity(), 'UTF-8')) . ', ' . $address->getRegion(); ?>"/>
                        <input type="hidden" id="instalemail" value="<?php echo $address->getEmail(); ?>"/>
                        <div class="panel panel-address confirm-payment-hide">
                            <div class="panel-body">
                                <div class="panel-title">Thông tin giao hàng</div>
                                <div class="shipping-information">
                                    <div class="address-text"><b>Họ tên:</b> <?php echo $address->getName(); ?></div>
                                    <div class="address-text"><b>Địa
                                            chỉ:</b> <?php echo $address->getStreetFull() . ', ' . ucfirst(mb_strtolower($address->getCity(), 'UTF-8')) . ', ' . $address->getRegion(); ?>
                                    </div>
                                    <div class="address-text"><b>Điện thoại:</b> <?php echo $address->getTelephone() ?>
                                    </div>
                                    <?php if ($address->getEmail() != ''): ?>
                                        <div class="address-text"><b>Email:</b> <?php echo $address->getEmail(); ?>
                                        </div><?php endif; ?>
                                    <?php if ($quote->getAffiliateCode()): ?>
                                        <div class="address-text">
                                            <b>Mã giới thiệu:</b>
                                            <?php echo $quote->getAffiliateCode() ?>
                                        </div>
                                    <?php endif; ?>
                                    <?php if ($address->getCustomerNotes() != ''): ?>
                                        <div class="address-text"><b>Ghi
                                            chú:</b> <?php echo $address->getCustomerNotes(); ?>
                                        </div><?php endif; ?>
                                </div>
                                <div class="checkout-freeship-block">
                                    <img src="<?php echo $this->getSkinUrl('images/delivery-truck.svg'); ?>"/>
                                    <span>Phong Vũ miễn phí vận chuyển cho các đơn hàng trị giá trên 500.000 đ <a
                                                href="https://phongvu.vn/landing/bieu-phi.html" target="_blank">(Tham khảo biểu phí dịch vụ)</a></span>
                                </div>
                            </div>
                        </div>

                        <?php echo $this->getChildHtml('right') ?>
                    </div>
                    <div class="col-md-5 col-sm-5 checkout-right-block">
                        <?php echo $this->getChildHtml('content') ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Content-->
    <!-- Start Footer-->
    <?php echo $this->getChildHtml('footer'); ?>
    <!-- End Footer-->
</div>

<!-- Google Tag Manager -->
<script>
    (function (w, d, s, l, i) {
        w[l] = w[l] || [];
        w[l].push({
            'gtm.start': new Date().getTime(), event: 'gtm.js'
        });
        var f = d.getElementsByTagName(s)[0],
            j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
        j.async = true;
        j.src =
            'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
        f.parentNode.insertBefore(j, f);
    })(window, document, 'script', 'dataLayer', 'GTM-W6CW7K7');
</script>
<!-- End Google Tag Manager -->

</body>
</html>
